### ISSUE TITLE
[Bug] Crash related to Full Inventory Warning

### ISSUE THREAD

**Issue by Charzard4261** [BiscuitDevelopment/SkyblockAddons#283]
**Describe the bug**
The game will crash due to the Full Inventory Warning Timer when not on a server.

**To Reproduce**
1. Go onto Hypixel Skyblock
2. Fill your inventory
3. Wait for first Full Inventory Warning
4. Disconnect
5. Wait for ~ 10 seconds
6. Crash

**Crash Report**
`---- Minecraft Crash Report ----`

`WARNING: coremods are present:
  SkyblockAddonsLoadingPlugin (SkyblockAddons-1.8.9-1.5.0-beta.16.jar)
Contact their authors BEFORE contacting forge`

`// There are four lights!`

`Time: 22/04/20 16:50
Description: Unexpected error`

`java.lang.NullPointerException: Unexpected error
	at codes.biscuit.skyblockaddons.utils.Utils.playLoudSound(Utils.java:442)
	at codes.biscuit.skyblockaddons.utils.InventoryUtils.showFullInventoryWarning(InventoryUtils.java:215)
	at codes.biscuit.skyblockaddons.utils.Scheduler$CommandType.execute(Scheduler.java:169)
	at codes.biscuit.skyblockaddons.utils.Scheduler.ticker(Scheduler.java:94)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_49_Scheduler_ticker_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:331)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1624)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**System Information**
 - OS: Windows 10
 - Mod Loader: Forge
 - Minecraft Version/Mod Loader Version: 1.8.9-11.15.1.2318
 - SkyblockAddons Version: 1.5.0-beta.16

**Other Installed Mods**
- jei_1.8.9-2.28.18.187
- moreoverlays-1.3-mc1.8.9
- MouseTweaks-2.6.2-mc1.8.9
- OptiFine_1.8.9_HD_U_L5

**Comment by Charzard4261** [comment]
Fixed by Biscuit in Beta v1.5.0-beta.17. Thank you!
