### ISSUE TITLE
[Bug] Cannot connect to Github to download language files

### ISSUE THREAD

**Issue by qinshuo145** [BiscuitDevelopment/SkyblockAddons#288]
[07:24:20] [Client thread/ERROR] [FML]: 1: ASM: mata.macrokey.handler.GuiEventHandler@5f1908c5 onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V

[07:24:20] [Client thread/ERROR] [FML]: 2: ASM: io.prplz.memoryfix.MemoryFix@1be6c991 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V

[07:24:20] [Client thread/ERROR] [FML]: 3: ASM: codes.biscuit.skyblockaddons.listeners.PlayerListener@40fc181d onClientTickMagma(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V

[07:24:20] [Client thread/ERROR] [FML]: 4: ASM: codes.biscuit.skyblockaddons.listeners.PlayerListener@40fc181d onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V

[07:24:20] [Client thread/ERROR] [FML]: 5: ASM: codes.biscuit.skyblockaddons.utils.Scheduler@3aac3f34 ticker(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V

[07:24:20] [Client thread/ERROR] [FML]: 6: ASM: me.allen.autofish.AutoFishEventHandler@782b12c9 onClientTickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V

[07:24:20] [Client thread/ERROR] [FML]: 7: ASM: com.orangemarshall.simplemod.togglesprint.ToggleSprint@7b4db485 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V

**Comment by qinshuo145** [comment]
[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: java.net.UnknownHostException: raw.githubusercontent.com

[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: 	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)

[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: 	at java.net.PlainSocketImpl.connect(Unknown Source)

[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: 	at java.net.SocksSocketImpl.connect(Unknown Source)

[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: 	at java.net.Socket.connect(Unknown Source)

[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: 	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)

[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: 	at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)

[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: 	at sun.net.NetworkClient.doConnect(Unknown Source)

[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: 	at sun.net.www.http.HttpClient.openServer(Unknown Source)

[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: 	at sun.net.www.http.HttpClient.openServer(Unknown Source)

[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: 	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)

[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: 	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)

[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)

[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)

[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: 	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)

[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: 	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)

[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: 	at java.security.AccessController.doPrivileged(Native Method)

[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: 	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)

[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)

[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)

[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)

[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source)

[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)

[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)

[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: 	at java.security.AccessController.doPrivileged(Native Method)

[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: 	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)

[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)

[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: 	at java.net.HttpURLConnection.getResponseCode(Unknown Source)

[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)

[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: 	at codes.biscuit.skyblockaddons.utils.ConfigValues.lambda$tryPullingLanguageOnline$0(ConfigValues.java:405)

[08:43:05] [Thread-15/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.ConfigValues:lambda$tryPullingLanguageOnline$0:418]: 	at java.lang.Thread.run(Unknown Source)

[08:43:05] [Thread-16/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.Utils:lambda$checkDisabledFeatures$2:426]: java.net.UnknownHostException: raw.githubusercontent.com

[08:43:05] [Thread-16/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.Utils:lambda$checkDisabledFeatures$2:426]: 	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)

[08:43:05] [Thread-16/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.Utils:lambda$checkDisabledFeatures$2:426]: 	at java.net.PlainSocketImpl.connect(Unknown Source)

[08:43:05] [Thread-16/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.Utils:lambda$checkDisabledFeatures$2:426]: 	at java.net.SocksSocketImpl.connect(Unknown Source)

[08:43:05] [Thread-16/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.Utils:lambda$checkDisabledFeatures$2:426]: 	at java.net.Socket.connect(Unknown Source)

[08:43:05] [Thread-16/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.Utils:lambda$checkDisabledFeatures$2:426]: 	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)

[08:43:05] [Thread-16/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.Utils:lambda$checkDisabledFeatures$2:426]: 	at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)

[08:43:05] [Thread-16/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.Utils:lambda$checkDisabledFeatures$2:426]: 	at sun.net.NetworkClient.doConnect(Unknown Source)

[08:43:05] [Thread-16/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.Utils:lambda$checkDisabledFeatures$2:426]: 	at sun.net.www.http.HttpClient.openServer(Unknown Source)

[08:43:05] [Thread-16/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.Utils:lambda$checkDisabledFeatures$2:426]: 	at sun.net.www.http.HttpClient.openServer(Unknown Source)

[08:43:05] [Thread-16/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.Utils:lambda$checkDisabledFeatures$2:426]: 	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)

[08:43:05] [Thread-16/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.Utils:lambda$checkDisabledFeatures$2:426]: 	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)

[08:43:05] [Thread-16/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.Utils:lambda$checkDisabledFeatures$2:426]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)

[08:43:05] [Thread-16/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.Utils:lambda$checkDisabledFeatures$2:426]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)

[08:43:05] [Thread-16/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.Utils:lambda$checkDisabledFeatures$2:426]: 	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)

[08:43:05] [Thread-16/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.Utils:lambda$checkDisabledFeatures$2:426]: 	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)

[08:43:05] [Thread-16/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.Utils:lambda$checkDisabledFeatures$2:426]: 	at java.security.AccessController.doPrivileged(Native Method)

[08:43:05] [Thread-16/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.Utils:lambda$checkDisabledFeatures$2:426]: 	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)

[08:43:05] [Thread-16/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.Utils:lambda$checkDisabledFeatures$2:426]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)

[08:43:05] [Thread-16/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.Utils:lambda$checkDisabledFeatures$2:426]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)

[08:43:05] [Thread-16/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.Utils:lambda$checkDisabledFeatures$2:426]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)

[08:43:05] [Thread-16/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.Utils:lambda$checkDisabledFeatures$2:426]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source)

[08:43:05] [Thread-16/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.Utils:lambda$checkDisabledFeatures$2:426]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)

[08:43:05] [Thread-16/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.Utils:lambda$checkDisabledFeatures$2:426]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)

[08:43:05] [Thread-16/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.Utils:lambda$checkDisabledFeatures$2:426]: 	at java.security.AccessController.doPrivileged(Native Method)

[08:43:05] [Thread-16/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.Utils:lambda$checkDisabledFeatures$2:426]: 	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)

[08:43:05] [Thread-16/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.Utils:lambda$checkDisabledFeatures$2:426]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)

[08:43:05] [Thread-16/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.Utils:lambda$checkDisabledFeatures$2:426]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)

[08:43:05] [Thread-16/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.Utils:lambda$checkDisabledFeatures$2:426]: 	at codes.biscuit.skyblockaddons.utils.Utils.lambda$checkDisabledFeatures$2(Utils.java:404)

[08:43:05] [Thread-16/INFO] [STDERR]: [codes.biscuit.skyblockaddons.utils.Utils:lambda$checkDisabledFeatures$2:426]: 	at java.lang.Thread.run(Unknown Source)

**Comment by ILikePlayingGames** [comment]
It looks like SkyblockAddons failed to connect to the server and download the required files. Were you connected to the Internet when this error occurred?

**Comment by ILikePlayingGames** [comment]
Closed since requested information was not provided
