### ISSUE TITLE
Game crashing when enchanting

### ISSUE THREAD

**Issue by etiennec78** [BiscuitDevelopment/SkyblockAddons#354]
Hi, every time I try to enchant an item, my game crash. I started my game with only Skyblock Addons and the bug is still here.

Crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SkyblockAddonsLoadingPlugin (SkyblockAddons-1.5.2-for-MC-1.8.9.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 05/08/20 18:24
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:241)
	at net.minecraft.client.renderer.ItemModelMesher.func_178084_b(ItemModelMesher.java:68)
	at net.minecraft.client.renderer.ItemModelMesher.func_178089_a(ItemModelMesher.java:41)
	at net.minecraft.client.renderer.entity.RenderItem.func_175042_a(RenderItem.java:344)
	at codes.biscuit.skyblockaddons.listeners.RenderListener.renderItem(RenderListener.java:1180)
	at codes.biscuit.skyblockaddons.listeners.RenderListener.drawText(RenderListener.java:871)
	at codes.biscuit.skyblockaddons.core.Feature.draw(Feature.java:236)
	at codes.biscuit.skyblockaddons.listeners.RenderListener.renderOverlays(RenderListener.java:296)
	at codes.biscuit.skyblockaddons.listeners.RenderListener.onRenderRegular(RenderListener.java:99)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_26_RenderListener_onRenderRegular_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:851)
	at net.minecraftforge.client.GuiIngameForge.renderExperience(GuiIngameForge.java:558)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:145)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1082)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:241)
	at net.minecraft.client.renderer.ItemModelMesher.func_178084_b(ItemModelMesher.java:68)
	at net.minecraft.client.renderer.ItemModelMesher.func_178089_a(ItemModelMesher.java:41)
	at net.minecraft.client.renderer.entity.RenderItem.func_175042_a(RenderItem.java:344)
	at codes.biscuit.skyblockaddons.listeners.RenderListener.renderItem(RenderListener.java:1180)
	at codes.biscuit.skyblockaddons.listeners.RenderListener.drawText(RenderListener.java:871)
	at codes.biscuit.skyblockaddons.core.Feature.draw(Feature.java:236)
	at codes.biscuit.skyblockaddons.listeners.RenderListener.renderOverlays(RenderListener.java:296)
	at codes.biscuit.skyblockaddons.listeners.RenderListener.onRenderRegular(RenderListener.java:99)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_26_RenderListener_onRenderRegular_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:851)
	at net.minecraftforge.client.GuiIngameForge.renderExperience(GuiIngameForge.java:558)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:145)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['etiennec78'/824413, l='MpServer', x=9,76, y=101,00, z=28,47], EntityOtherPlayerMP['KreamyPuff'/10864634, l='MpServer', x=9,75, y=112,99, z=28,47]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 0,00,100,00,0,00 - World: (0,100,0), Chunk: (at 0,6,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2962 game time, 4967 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 134 total; [EntityCreeper['Creeper'/10864549, l='MpServer', x=-13,31, y=99,00, z=41,31], EntityArmorStand['§8[§7Lv1§8] §cCreeper §a80§f/§a80§c?'/10864550, l='MpServer', x=-13,28, y=100,69, z=41,28], EntityArmorStand['Armor Stand'/10864545, l='MpServer', x=-9,50, y=100,00, z=31,50], EntityArmorStand['Armor Stand'/10864544, l='MpServer', x=-3,50, y=100,00, z=37,50], EntityOtherPlayerMP['KreamyPuff'/10864634, l='MpServer', x=9,75, y=112,99, z=28,47], EntityArmorStand['Armor Stand'/10864546, l='MpServer', x=-15,50, y=100,00, z=43,50], EntityArmorStand['Armor Stand'/10864557, l='MpServer', x=-15,50, y=100,00, z=37,50], EntityArmorStand['Armor Stand'/10864559, l='MpServer', x=10,03, y=98,53, z=23,47], EntityArmorStand['Armor Stand'/10864558, l='MpServer', x=-13,50, y=102,56, z=67,50], EntityCreeper['Creeper'/10864553, l='MpServer', x=-14,28, y=99,00, z=41,38], EntityArmorStand['§8[§7Lv1§8] §cCreeper §a80§f/§a80§c?'/10872745, l='MpServer', x=-15,75, y=100,69, z=42,28], EntityCreeper['Creeper'/10872744, l='MpServer', x=-15,72, y=99,00, z=42,31], EntityArmorStand['§8[§7Lv1§8] §cCreeper §a80§f/§a80§c?'/10864554, l='MpServer', x=-14,19, y=100,69, z=41,34], EntityArmorStand['Armor Stand'/10864565, l='MpServer', x=2,50, y=100,00, z=25,50], EntityArmorStand['Armor Stand'/10864564, l='MpServer', x=-15,50, y=100,00, z=25,50], EntityArmorStand['Armor Stand'/10864567, l='MpServer', x=-9,50, y=100,00, z=43,50], EntityArmorStand['Armor Stand'/10864566, l='MpServer', x=2,50, y=100,00, z=37,50], EntityArmorStand['Armor Stand'/10864561, l='MpServer', x=9,78, y=98,56, z=22,78], EntityArmorStand['Armor Stand'/10864560, l='MpServer', x=10,00, y=99,09, z=23,47], EntityArmorStand['Armor Stand'/10864563, l='MpServer', x=-3,50, y=100,00, z=25,50], EntityArmorStand['Armor Stand'/10864562, l='MpServer', x=9,38, y=99,25, z=23,28], EntityArmorStand['§8[§7Lv1§8] §cEnderman §a160§f/§a160§c?'/10864575, l='MpServer', x=-10,75, y=102,00, z=43,81], EntityEnderman['Enderman'/10864574, l='MpServer', x=-10,72, y=99,00, z=43,84], EntityItemFrame['entity.ItemFrame.name'/10864516, l='MpServer', x=6,03, y=101,50, z=18,50], EntityVillager['Villager'/10864513, l='MpServer', x=2,50, y=100,00, z=43,50], EntityItemFrame['entity.ItemFrame.name'/10864512, l='MpServer', x=7,03, y=95,50, z=36,50], EntityItemFrame['entity.ItemFrame.name'/10864515, l='MpServer', x=2,97, y=102,50, z=63,50], EntityItemFrame['entity.ItemFrame.name'/10864514, l='MpServer', x=2,97, y=101,50, z=63,50], EntityArmorStand['Armor Stand'/10864524, l='MpServer', x=-9,50, y=100,00, z=37,50], EntityRabbit['Rabbit'/10864527, l='MpServer', x=-7,50, y=100,00, z=34,94], EntityArmorStand['Armor Stand'/10864533, l='MpServer', x=9,44, y=98,56, z=25,72], EntityArmorStand['Armor Stand'/10864532, l='MpServer', x=9,66, y=99,09, z=26,41], EntityArmorStand['Armor Stand'/10864535, l='MpServer', x=-21,50, y=100,00, z=25,50], EntityArmorStand['Armor Stand'/10864534, l='MpServer', x=9,03, y=99,25, z=26,22], EntityArmorStand['Armor Stand'/10864529, l='MpServer', x=2,50, y=100,00, z=31,50], EntityArmorStand['Armor Stand'/10864531, l='MpServer', x=9,69, y=98,53, z=26,41], EntityArmorStand['Armor Stand'/10864530, l='MpServer', x=9,50, y=99,44, z=32,50], EntityArmorStand['§8[§7Lv1§8] §cBlaze §a160§f/§a160§c?'/10864541, l='MpServer', x=-19,94, y=101,00, z=26,25], EntityBlaze['Blaze'/10864540, l='MpServer', x=-19,94, y=99,00, z=26,38], EntityArmorStand['§8[§7Lv1§8] §cBlaze §a160§f/§a160§c?'/10864543, l='MpServer', x=-20,81, y=101,00, z=26,66], EntityBlaze['Blaze'/10864542, l='MpServer', x=-20,75, y=99,00, z=26,63], EntityArmorStand['§8[§7Lv1§8] §cBlaze §a160§f/§a160§c?'/10864537, l='MpServer', x=-21,56, y=101,00, z=27,44], EntityBlaze['Blaze'/10864536, l='MpServer', x=-21,53, y=99,00, z=27,47], EntityArmorStand['§8[§7Lv1§8] §cBlaze §a160§f/§a160§c?'/10864539, l='MpServer', x=-22,56, y=101,00, z=25,91], EntityEnderman['Enderman'/10890648, l='MpServer', x=-11,50, y=100,00, z=40,94], EntityBlaze['Blaze'/10864538, l='MpServer', x=-22,59, y=99,00, z=25,97], EntityArmorStand['§8[§7Lv1§8] §cEnderman §a160§f/§a160§c?'/10890649, l='MpServer', x=-11,47, y=103,00, z=40,91], EntityArmorStand['Armor Stand'/10864613, l='MpServer', x=9,88, y=99,94, z=24,84], EntityArmorStand['Armor Stand'/10864612, l='MpServer', x=9,94, y=99,72, z=24,78], EntityArmorStand['Armor Stand'/10864615, l='MpServer', x=9,97, y=99,72, z=24,81], EntityEnderman['Enderman'/10878951, l='MpServer', x=-9,34, y=99,00, z=41,66], EntityArmorStand['Armor Stand'/10864614, l='MpServer', x=9,97, y=99,91, z=24,81], EntityArmorStand['Armor Stand'/10864609, l='MpServer', x=9,94, y=99,44, z=24,75], EntityArmorStand['Armor Stand'/10864608, l='MpServer', x=9,81, y=99,41, z=24,78], EntityArmorStand['Armor Stand'/10864611, l='MpServer', x=9,97, y=99,56, z=24,78], EntityArmorStand['Armor Stand'/10864610, l='MpServer', x=9,84, y=99,91, z=24,75], EntityArmorStand['Armor Stand'/10864617, l='MpServer', x=9,97, y=98,50, z=25,66], EntityArmorStand['Armor Stand'/10864616, l='MpServer', x=9,84, y=99,72, z=24,81], EntityArmorStand['§8[§7Lv1§8] §cEnderman §a160§f/§a160§c?'/10878952, l='MpServer', x=-9,38, y=102,00, z=41,69], EntityArmorStand['Armor Stand'/10864619, l='MpServer', x=-21,50, y=100,00, z=31,50], EntityArmorStand['Armor Stand'/10864618, l='MpServer', x=9,81, y=98,56, z=23,91], EntityArmorStand['§8[§7Lv56§8] §fetiennec78's Rock'/10864633, l='MpServer', x=7,50, y=100,50, z=7,50], EntityArmorStand['Armor Stand'/10864632, l='MpServer', x=7,50, y=98,50, z=7,50], EntityOtherPlayerMP['KreamyPuff'/10864634, l='MpServer', x=9,75, y=112,99, z=28,47], EntityArmorStand['Armor Stand'/10864581, l='MpServer', x=9,81, y=99,06, z=24,81], EntityArmorStand['Armor Stand'/10864580, l='MpServer', x=10,38, y=98,56, z=25,19], EntityArmorStand['Armor Stand'/10864583, l='MpServer', x=9,03, y=98,56, z=24,88], EntityArmorStand['Armor Stand'/10864582, l='MpServer', x=9,84, y=99,25, z=24,72], EntityArmorStand['Armor Stand'/10864577, l='MpServer', x=-15,50, y=100,00, z=31,50], EntityArmorStand['Armor Stand'/10864576, l='MpServer', x=-9,50, y=100,00, z=25,50], EntityArmorStand['Armor Stand'/10864579, l='MpServer', x=9,94, y=99,06, z=24,75], EntityArmorStand['§8[§7Lv1§8] §cBlaze §a160§f/§a160§c?'/10865091, l='MpServer', x=-23,19, y=101,00, z=27,16], EntityArmorStand['Armor Stand'/10864578, l='MpServer', x=-3,50, y=100,00, z=31,50], EntityBlaze['Blaze'/10865090, l='MpServer', x=-23,16, y=99,00, z=27,13], EntityArmorStand['Armor Stand'/10864589, l='MpServer', x=10,38, y=99,50, z=25,19], EntityArmorStand['Armor Stand'/10864588, l='MpServer', x=9,94, y=100,06, z=24,75], EntityArmorStand['Armor Stand'/10864591, l='MpServer', x=9,84, y=100,25, z=24,72], EntityArmorStand['Armor Stand'/10864590, l='MpServer', x=9,81, y=100,06, z=24,81], EntityArmorStand['Armor Stand'/10864585, l='MpServer', x=9,97, y=99,31, z=24,78], EntityArmorStand['Armor Stand'/10864584, l='MpServer', x=9,94, y=99,06, z=24,84], EntityArmorStand['Armor Stand'/10864587, l='MpServer', x=9,88, y=101,16, z=24,81], EntityArmorStand['Armor Stand'/10864586, l='MpServer', x=9,84, y=99,25, z=24,84], EntityArmorStand['Armor Stand'/10864597, l='MpServer', x=9,84, y=100,25, z=24,84], EntityArmorStand['Armor Stand'/10864596, l='MpServer', x=9,91, y=101,13, z=24,78], EntityArmorStand['Armor Stand'/10864599, l='MpServer', x=10,09, y=98,88, z=24,50], EntityEnderman['Enderman'/10866903, l='MpServer', x=-8,28, y=99,00, z=45,28], EntityArmorStand['Armor Stand'/10864598, l='MpServer', x=10,09, y=101,06, z=24,53], EntityArmorStand['Armor Stand'/10864593, l='MpServer', x=9,94, y=100,06, z=24,84], EntityArmorStand['Armor Stand'/10864592, l='MpServer', x=9,63, y=101,06, z=24,63], EntityArmorStand['Armor Stand'/10864595, l='MpServer', x=9,97, y=100,31, z=24,78], EntityArmorStand['Armor Stand'/10864594, l='MpServer', x=9,88, y=101,16, z=24,81], EntityArmorStand['Armor Stand'/10864605, l='MpServer', x=9,97, y=99,41, z=24,84], EntityArmorStand['Armor Stand'/10864604, l='MpServer', x=9,72, y=99,06, z=25,06], EntityArmorStand['Armor Stand'/10864607, l='MpServer', x=9,84, y=99,53, z=24,81], EntityArmorStand['Armor Stand'/10864606, l='MpServer', x=9,88, y=99,53, z=24,88], EntityArmorStand['Armor Stand'/10864601, l='MpServer', x=9,56, y=98,88, z=24,81], EntityArmorStand['Armor Stand'/10864600, l='MpServer', x=10,09, y=98,88, z=25,09], EntityArmorStand['§8[§7Lv1§8] §cEnderman §a160§f/§a160§c?'/10866904, l='MpServer', x=-8,25, y=102,00, z=45,25], EntityArmorStand['Armor Stand'/10864603, l='MpServer', x=10,16, y=99,13, z=24,81], EntityRabbit['Rabbit'/10898136, l='MpServer', x=-11,50, y=99,00, z=39,50], EntityArmorStand['Armor Stand'/10864602, l='MpServer', x=9,72, y=99,09, z=24,56], EntityArmorStand['§7Click HERE to remove'/10866724, l='MpServer', x=13,50, y=100,19, z=42,00], EntityArmorStand['Armor Stand'/10866465, l='MpServer', x=-16,50, y=98,44, z=17,50], EntityArmorStand['§7Click HERE to remove'/10866721, l='MpServer', x=-1,50, y=100,19, z=42,00], EntityArmorStand['§aThe Barn'/10866720, l='MpServer', x=-1,50, y=100,56, z=42,00], EntityArmorStand['§aDeep Caverns'/10866723, l='MpServer', x=13,50, y=100,56, z=42,00], EntityArmorStand['§bTravel to:'/10866722, l='MpServer', x=13,50, y=100,94, z=42,00], EntityPlayerSP['etiennec78'/824413, l='MpServer', x=9,76, y=101,00, z=28,47], EntityRabbit['Rabbit'/10865671, l='MpServer', x=-9,75, y=99,78, z=35,47], EntityArmorStand['§bTravel to:'/10866717, l='MpServer', x=6,50, y=100,94, z=41,50], EntityArmorStand['§e§lCLICK'/10866716, l='MpServer', x=2,50, y=99,84, z=43,50], EntityArmorStand['§bTravel to:'/10866719, l='MpServer', x=-1,50, y=100,94, z=42,00], EntityArmorStand['§aHub Island'/10866718, l='MpServer', x=6,50, y=100,56, z=41,50], EntityRabbit['Rabbit'/10888731, l='MpServer', x=-11,38, y=99,00, z=35,97], EntityArmorStand['Jerry'/10866715, l='MpServer', x=2,50, y=100,09, z=43,50], EntityArmorStand['§8[§7Lv1§8] §cCreeper §a80§f/§a80§c?'/10894438, l='MpServer', x=-13,63, y=100,69, z=45,06], EntityCreeper['Creeper'/10894437, l='MpServer', x=-13,59, y=99,00, z=45,03], EntityRabbit['Rabbit'/10877282, l='MpServer', x=-8,50, y=100,00, z=34,94], EntityItemFrame['entity.ItemFrame.name'/10864501, l='MpServer', x=7,03, y=95,50, z=38,50], EntityItemFrame['entity.ItemFrame.name'/10864500, l='MpServer', x=7,03, y=95,50, z=39,50], EntityItemFrame['entity.ItemFrame.name'/10864503, l='MpServer', x=8,97, y=95,50, z=38,50], EntityItemFrame['entity.ItemFrame.name'/10864502, l='MpServer', x=8,97, y=95,50, z=39,50], EntityItemFrame['entity.ItemFrame.name'/10864499, l='MpServer', x=8,97, y=95,50, z=40,50], EntityItemFrame['entity.ItemFrame.name'/10864509, l='MpServer', x=7,03, y=95,50, z=37,50], EntityItemFrame['entity.ItemFrame.name'/10864508, l='MpServer', x=8,97, y=95,50, z=36,50], EntityItemFrame['entity.ItemFrame.name'/10864511, l='MpServer', x=7,03, y=95,50, z=34,50], EntityItemFrame['entity.ItemFrame.name'/10864510, l='MpServer', x=7,03, y=95,50, z=35,50], EntityItemFrame['entity.ItemFrame.name'/10864505, l='MpServer', x=8,97, y=95,50, z=37,50], EntityItemFrame['entity.ItemFrame.name'/10864504, l='MpServer', x=7,03, y=95,50, z=40,50], EntityItemFrame['entity.ItemFrame.name'/10864507, l='MpServer', x=8,97, y=95,50, z=34,50], EntityItemFrame['entity.ItemFrame.name'/10864506, l='MpServer', x=8,97, y=95,50, z=35,50], EntityArmorStand['§8? §cNo Destination'/10864709, l='MpServer', x=4,50, y=98,44, z=17,50], EntityCreeper['Creeper'/10884180, l='MpServer', x=-15,94, y=99,00, z=41,38], EntityArmorStand['§8[§7Lv1§8] §cCreeper §a80§f/§a80§c?'/10884181, l='MpServer', x=-15,97, y=100,69, z=41,34]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (Hypixel) <- vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 989181416 bytes (943 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	skyblockaddons{1.5.2} [SkyBlock Addons] (SkyblockAddons-1.5.2-for-MC-1.8.9.jar) 
	Loaded coremods (and transformers): 
SkyblockAddonsLoadingPlugin (SkyblockAddons-1.5.2-for-MC-1.8.9.jar)
  codes.biscuit.skyblockaddons.tweaker.SkyblockAddonsTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 425.31' Renderer: 'GeForce 920M/PCIe/SSE2'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: GeForce 920M/PCIe/SSE2 GL version 4.6.0 NVIDIA 425.31, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Hypixel Skyblock
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz

**Comment by etiennec78** [comment]
A helper on discord find a solution: use the /lang english command on hypixel and the bug will be fixed
