### ISSUE TITLE
SkyblockAddons CRASHING[Bug] <Title Here>

### ISSUE THREAD

**Issue by ToonsMC** [BiscuitDevelopment/SkyblockAddons#405]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
When i go into block menu in my home it crashes and it only happens when sba is in the mods folder

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Go to 'Housing'
2. Go to your 'Home'(/home)
3. Once your in your home, click on 'Menu'
4. Click The 'Bricks(Blocks Menu)'
5. Crashes

**Expected behavior**
Only happens when have the current latest version of skyblockaddons

**Crash Report**
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ModTweaker (Patcher-1.3 (1.8.9).jar)
  PatcherTweaker (Patcher-1.3 (1.8.9).jar)
  SkyblockAddonsLoadingPlugin (SkyblockAddons-1.5.3-for-MC-1.8.9.jar)
  CTJSLoadingPlugin (ctjs-1.3.0-1.8.9.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 9/18/20 1:32 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at net.minecraft.item.ItemMap.func_77624_a(ItemMap.java:282)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:587)
	at codes.biscuit.skyblockaddons.core.npc.NPCUtils.isSellMerchant(NPCUtils.java:46)
	at codes.biscuit.skyblockaddons.asm.hooks.GuiChestHook.handleMouseClick(GuiChestHook.java:351)
	at net.minecraft.client.gui.inventory.GuiChest.func_146984_a(SourceFile)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:388)
	at net.minecraft.client.gui.inventory.GuiChest.func_73864_a(SourceFile)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:555)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:524)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.item.ItemMap.func_77624_a(ItemMap.java:282)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:587)
	at codes.biscuit.skyblockaddons.core.npc.NPCUtils.isSellMerchant(NPCUtils.java:46)
	at codes.biscuit.skyblockaddons.asm.hooks.GuiChestHook.handleMouseClick(GuiChestHook.java:351)
	at net.minecraft.client.gui.inventory.GuiChest.func_146984_a(SourceFile)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:388)
	at net.minecraft.client.gui.inventory.GuiChest.func_73864_a(SourceFile)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:555)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:524)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiChest

-- Affected level --
Details:
	Level name: MpServer
	All players: 3 total; [EntityPlayerSP['Thoughted'/487664, l='MpServer', x=20.64, y=106.94, z=-35.23], EntityOtherPlayerMP['Carpenter'/9928, l='MpServer', x=-2.50, y=110.00, z=-57.50], EntityOtherPlayerMP['JuliermePlayer'/9931, l='MpServer', x=20.62, y=118.42, z=-35.26]]
	Chunk stats: MultiplayerChunkCache: 330, 330
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 0.00,100.00,0.00 - World: (0,100,0), Chunk: (at 0,6,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 70 game time, 1 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 10 total; [EntityOtherPlayerMP['Carpenter'/9928, l='MpServer', x=-2.50, y=110.00, z=-57.50], EntityLeashKnot['entity.LeashKnot.name'/9927, l='MpServer', x=0.50, y=0.50, z=0.50], EntityOtherPlayerMP['Carpenter'/9928, l='MpServer', x=-2.50, y=110.00, z=-57.50], EntityOtherPlayerMP['JuliermePlayer'/9931, l='MpServer', x=20.62, y=118.42, z=-35.26], EntityOtherPlayerMP['JuliermePlayer'/9931, l='MpServer', x=20.62, y=118.42, z=-35.26], EntityArmorStand['§a? §aWarp To §k!§2Island §9Hub§r§k!'/9932, l='MpServer', x=20.50, y=101.44, z=-25.50], EntityPlayerSP['Thoughted'/487664, l='MpServer', x=8.50, y=65.00, z=8.50], EntityArmorStand['§a? §aWarp To §k!§2Island §9Hub§r§k!'/9933, l='MpServer', x=20.50, y=102.44, z=-29.50], EntityPlayerSP['Thoughted'/487664, l='MpServer', x=8.50, y=65.00, z=8.50], EntityPlayerSP['Thoughted'/487664, l='MpServer', x=20.64, y=106.94, z=-35.23]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (Hypixel) <- vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:402)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	ct.js modules: [Module{name=CustomRank,folder=.\config\ChatTriggers\modules\CustomRank,metadata=ModuleMetadata(name=CustomRank, version=1.5, entry=index.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Shit module, shit idea, shit shit., requires=[SettingsManager], helpMessage=null, ignored=null, isRequired=false)}, Module{name=DeepProxy,folder=.\config\ChatTriggers\modules\DeepProxy,metadata=ModuleMetadata(name=DeepProxy, version=2.0.0, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=Ecolsson, description=null, requires=null, helpMessage=null, ignored=null, isRequired=false)}, Module{name=DungeonItemQuality,folder=.\config\ChatTriggers\modules\DungeonItemQuality,metadata=ModuleMetadata(name=DungeonItemQuality, version=1.0, entry=index.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=null, requires=[], helpMessage=null, ignored=null, isRequired=false)}, Module{name=DungeonUtilities,folder=.\config\ChatTriggers\modules\DungeonUtilities,metadata=ModuleMetadata(name=DungeonUtilities, version=0.9.9, entry=loader.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=null, requires=[SettingsManager, PersistentData], helpMessage=null, ignored=null, isRequired=false)}, Module{name=FakeRNGDrop,folder=.\config\ChatTriggers\modules\FakeRNGDrop,metadata=ModuleMetadata(name=FakeRNGDrop, version=null, entry=index.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Fake RNG Drops v2!, requires=[SettingsManager], helpMessage=null, ignored=null, isRequired=false)}, Module{name=NameHistory,folder=.\config\ChatTriggers\modules\NameHistory,metadata=ModuleMetadata(name=NameHistory, version=1.0.0, entry=main.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Adds /namehistory <username> command to see a user's name history, requires=[request], helpMessage=null, ignored=null, isRequired=false)}, Module{name=PersistentData,folder=.\config\ChatTriggers\modules\PersistentData,metadata=ModuleMetadata(name=PersistentData, version=1.1.3, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Easily store data that persist between game and ct reloads, requires=[DeepProxy], helpMessage=null, ignored=null, isRequired=false)}, Module{name=Promise,folder=.\config\ChatTriggers\modules\Promise,metadata=ModuleMetadata(name=Promise, version=1.0.0, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Promise polyfill for 1.0.0, requires=null, helpMessage=null, ignored=null, isRequired=false)}, Module{name=request,folder=.\config\ChatTriggers\modules\request,metadata=ModuleMetadata(name=request, version=2.0.0, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=Ecolsson, description=A nicer alternative to XMLHttpRequest with a promise-like API. See the README.md for a full api description, requires=[Promise], helpMessage=null, ignored=null, isRequired=false)}, Module{name=SettingsManager,folder=.\config\ChatTriggers\modules\SettingsManager,metadata=ModuleMetadata(name=SettingsManager, version=1.2.1, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Autogenerates a settings file and gui based on the object created and registers. Example usage can be found in UseExample.js, requires=null, helpMessage=null, ignored=null, isRequired=false)}]
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 317067648 bytes (302 MB) / 1275068416 bytes (1216 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 62, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_L5 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	skyblockaddons{1.5.3} [SkyBlock Addons] (SkyblockAddons-1.5.3-for-MC-1.8.9.jar) 
	UCHIJA	notenoughupdates{1.3-REL} [NotEnoughUpdates] (NotEnoughUpdates-1.3.1-REL.jar) 
	UCHIJA	patcher{1.3} [Patcher] (Patcher-1.3 (1.8.9).jar) 
	UCHIJA	ct.js{1.3.0} [ChatTriggers] (ctjs-1.3.0-1.8.9.jar) 
	UCHIJA	modcore{0.1.42} [ModCore] (Sk1er Modcore-0.1.42 (1.8.9).jar) 
	Loaded coremods (and transformers): 
ModTweaker (Patcher-1.3 (1.8.9).jar)
  club.sk1er.patcher.tweaker.other.ModClassTransformer
PatcherTweaker (Patcher-1.3 (1.8.9).jar)
  club.sk1er.mods.core.forge.ClassTransformer
  club.sk1er.patcher.tweaker.ClassTransformer
SkyblockAddonsLoadingPlugin (SkyblockAddons-1.5.3-for-MC-1.8.9.jar)
  codes.biscuit.skyblockaddons.tweaker.SkyblockAddonsTransformer
CTJSLoadingPlugin (ctjs-1.3.0-1.8.9.jar)
  com.chattriggers.ctjs.launch.plugin.CTJSTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 432.00' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: v12F32x_Skyblock_Pack_1.8.9.zip, !   §6§lDeos 2k Pack§r§6 (v1.3).zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_L5
	OptiFine Build: 20191204-143016
	Render Distance Chunks: 20
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 432.00

**System Information**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318.1.8.9
 - SkyblockAddons Version: 1.5.3

**Other Installed Mods**
- ctjs-1.3.0-1.8.9
- NotEnoughUpdates-1.3.1-REL
- OptiFine_1.8.9_HD_U_L5
- Patcher-1.3 (1.8.9)

**Comment by Justin2528** [comment]
Known Bug

**Comment by ILikePlayingGames** [comment]
Yes we are aware and a fix will be released soon

**Comment by ILikePlayingGames** [comment]
Fixed in 1.5.4
