### ISSUE TITLE
[Bug] Crash when using chroma

### ISSUE THREAD

**Issue by ffoxxeyy** [BiscuitDevelopment/SkyblockAddons#446]
**Describe the bug**
Crashing when using chroma.

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Enable Chroma
2. Go into skyblock
3. See error

**Expected behavior**
-

**Screenshots**
-

**Crash Report**
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLLoadingPlugin (MemoryFix-0.3.jar)
  FMLLoadingPlugin (Scrollable Tooltips-1.2 (1.8.9).jar)
  SkyblockAddonsLoadingPlugin (SkyblockAddons-1.6.0-beta.6-for-MC-1.8.9.jar)
  Main (OldAnimationsMod v2.4.2 FORGE MC1.8.9.jar)
  FMLLoadingPlugin (MouseDelayFix-1.0.jar)
  FMLLoadingPlugin (Skypixel-0.0.6.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 10/25/20 2:26 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at codes.biscuit.skyblockaddons.misc.ChromaManager.getChromaColor(ChromaManager.java:53)
    at codes.biscuit.skyblockaddons.misc.ChromaManager.getChromaColor(ChromaManager.java:36)
    at codes.biscuit.skyblockaddons.config.ConfigValues.getColor(ConfigValues.java:695)
    at codes.biscuit.skyblockaddons.config.ConfigValues.getColor(ConfigValues.java:703)
    at codes.biscuit.skyblockaddons.listeners.RenderListener.drawText(RenderListener.java:656)
    at codes.biscuit.skyblockaddons.core.Feature.draw(Feature.java:321)
    at codes.biscuit.skyblockaddons.listeners.RenderListener.renderOverlays(RenderListener.java:344)
    at codes.biscuit.skyblockaddons.listeners.RenderListener.onRenderRegular(RenderListener.java:141)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_115_RenderListener_onRenderRegular_Post.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:851)
    at net.minecraftforge.client.GuiIngameForge.renderExperience(GuiIngameForge.java:558)
    at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:145)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1396)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at codes.biscuit.skyblockaddons.misc.ChromaManager.getChromaColor(ChromaManager.java:53)
    at codes.biscuit.skyblockaddons.misc.ChromaManager.getChromaColor(ChromaManager.java:36)
    at codes.biscuit.skyblockaddons.config.ConfigValues.getColor(ConfigValues.java:695)
    at codes.biscuit.skyblockaddons.config.ConfigValues.getColor(ConfigValues.java:703)
    at codes.biscuit.skyblockaddons.listeners.RenderListener.drawText(RenderListener.java:656)
    at codes.biscuit.skyblockaddons.core.Feature.draw(Feature.java:321)
    at codes.biscuit.skyblockaddons.listeners.RenderListener.renderOverlays(RenderListener.java:344)
    at codes.biscuit.skyblockaddons.listeners.RenderListener.onRenderRegular(RenderListener.java:141)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_115_RenderListener_onRenderRegular_Post.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:851)
    at net.minecraftforge.client.GuiIngameForge.renderExperience(GuiIngameForge.java:558)
    at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:145)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['Kitssunne'/15141047, l='MpServer', x=9.62, y=128.00, z=36.56]]
    Chunk stats: MultiplayerChunkCache: 16, 16
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: 0.00,100.00,0.00 - World: (0,100,0), Chunk: (at 0,6,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 11 game time, 6010 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 2 total; [EntityVillager['Villager'/5559436, l='MpServer', x=44.50, y=102.00, z=52.44], EntityPlayerSP['Kitssunne'/15141047, l='MpServer', x=9.62, y=128.00, z=36.56]]
    Retry entities: 0 total; []
    Server brand: BungeeCord (Hypixel) <- vanilla
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:417)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    CPU: 8x AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx 
    Java Version: 1.8.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 2048530136 bytes (1953 MB) / 3140747264 bytes (2995 MB) up to 3140747264 bytes (2995 MB)
    JVM Flags: 26 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -Xms3G -Xmn768m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_I7 16 mods loaded, 16 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA    mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJA    FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
    UCHIJA    Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
    UCHIJA    mousedelayfix{1.0} [MouseDelayFix] (minecraft.jar) 
    UCHIJA    oldanimations{2.4.2} [OldAnimationsMod] (minecraft.jar) 
    UCHIJA    modcore{0.1.47} [ModCore] (Sk1er Modcore-0.1.47 (1.8.9).jar) 
    UCHIJA    fullbright{1.2} [Fullbright] (1.8.9-Fullbright-v1.2.1.jar) 
    UCHIJA    skyblockmod{1.1} [Powns' Skyblock EXP Mod] ([1.8.9] Powns Skyblock Mod - 1.1.jar) 
    UCHIJA    memoryfix{0.3} [MemoryFix] (MemoryFix-0.3.jar) 
    UCHIJA    notenoughupdates{1.4-REL} [NotEnoughUpdates] (NotEnoughUpdates-1.4.6-BETA.jar) 
    UCHIJA    orangesimplemod{1.0} [orangesimplemod] (Orange's+Simple+Mods-1.2.jar) 
    UCHIJA    text_overflow_scroll{1.2} [Scrollable Tooltips] (Scrollable Tooltips-1.2 (1.8.9).jar) 
    UCHIJA    skyblockaddons{1.6.0-beta.6} [SkyblockAddons] (SkyblockAddons-1.6.0-beta.6-for-MC-1.8.9.jar) 
    UCHIJA    skyblockstatistics{1.1.0} [SkyblockStatistics] (SkyblockStats-1.1.0-1.8.9.jar) 
    UCHIJA    skypixel{0.0.6} [Skypixel] (Skypixel-0.0.6.jar) 
    UCHIJA    sk1er_fullscreen{1.0} [Sk1er Fullscreen] (Windowed Fullscreen-1.0 (1.8.9).jar) 
    Loaded coremods (and transformers): 
FMLLoadingPlugin (MemoryFix-0.3.jar)
  io.prplz.memoryfix.ClassTransformer
FMLLoadingPlugin (Scrollable Tooltips-1.2 (1.8.9).jar)
  club.sk1er.mods.core.forge.ClassTransformer
  club.sk1er.mods.overflowscroll.forge.ClassTransformer
SkyblockAddonsLoadingPlugin (SkyblockAddons-1.6.0-beta.6-for-MC-1.8.9.jar)
  codes.biscuit.skyblockaddons.tweaker.SkyblockAddonsTransformer
Main (OldAnimationsMod v2.4.2 FORGE MC1.8.9.jar)
  com.spiderfrog.main.ClassTransformer
FMLLoadingPlugin (MouseDelayFix-1.0.jar)
  io.prplz.mousedelayfix.ClassTransformer
FMLLoadingPlugin (Skypixel-0.0.6.jar)
  io.prplz.skypixel.asm.ClassTransformer
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13596 Compatibility Profile Context 20.10 27.20.1002.34' Renderer: 'AMD Radeon(TM) Vega 8 Graphics'
    Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
    LWJGL: 2.9.4
    OpenGL: AMD Radeon(TM) Vega 8 Graphics GL version 4.6.13596 Compatibility Profile Context 20.10 27.20.1002.34, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

    Using VBOs: No
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: 1.14 default textures.zip, §2§lDungeons Pack v2.zip
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    CPU: 8x AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx 

**System Information**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: 1.15.1.2318
 - SkyblockAddons Version: 1.6 beta 6

**Other Installed Mods**
Says them in the crash report

**Additional info**
-

**Comment by ffoxxeyy** [comment]
Bump?

**Comment by IRONM00N** [comment]
Pretty sure this is fixed in the latest beta.

**Comment by RobotHanzo** [comment]
> Pretty sure this is fixed in the latest beta.

I don't think so, latest compiled from development branch crashes too

**Comment by IRONM00N** [comment]
GitHub isn’t up to date with the latest beta

**Comment by RobotHanzo** [comment]
> GitHub isn’t up to date with the latest beta

development branch is newer than beta? or am I wrong

**Comment by IRONM00N** [comment]
You are incorrect, the newest betas are no longer being put onto GitHub due to people building it

**Comment by RobotHanzo** [comment]
Oh, didn't know that
thanks for correcting

**Comment by Phoube** [comment]
Closing because 1.6.0 *should* have fixed this. Feel free to re-open if not!
