### ISSUE TITLE
Build failed for last dev version

### ISSUE THREAD

**Issue by konoashi** [BiscuitDevelopment/SkyblockAddons#471]
17:13:45.971 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Execute executeTests for :test'
17:13:45.971 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Execute executeTests for :test' completed
17:13:45.971 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Fingerprinting property binResultsDir (Output) for task ':test'
17:13:45.973 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Fingerprinting property reports.enabledReports.html.destination (Output) for task ':test'
17:13:45.981 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Fingerprinting property reports.enabledReports.junitXml.destination (Output) for task ':test'
17:13:45.985 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Fingerprinting property reports.html.destination (Output) for task ':test'
17:13:45.985 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Fingerprinting property reports.junitXml.destination (Output) for task ':test'
17:13:45.986 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Removed task artifact state for {} from context.
17:13:45.986 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':test'
17:13:45.986 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Task :test'
17:13:45.986 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Task :test' completed
17:13:45.987 [INFO] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] :test (Thread[Task worker for ':' Thread 2,5,main]) completed. Took 2.771 secs.
17:13:45.987 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Task worker for ':' Thread 2: released lock on :
17:13:45.987 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Worker lease root.1.23 completed (1 worker(s) in use)
17:13:45.987 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Task worker for ':' Thread 2: released lock on root.1.23
17:13:45.987 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':',5,main]] finished, busy: 0.06 secs, idle: 11.526 secs
17:13:45.987 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':' Thread 7,5,main]] finished, busy: 0.0 secs, idle: 11.582 secs
17:13:45.987 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':' Thread 5,5,main]] finished, busy: 0.0 secs, idle: 11.582 secs
17:13:45.987 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Daemon worker Thread 4,5,main]] finished, busy: 0.0 secs, idle: 11.582 secs
17:13:45.987 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':' Thread 2,5,main]] finished, busy: 11.431 secs, idle: 0.153 secs
17:13:45.987 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':' Thread 4,5,main]] finished, busy: 0.0 secs, idle: 11.583 secs
17:13:45.987 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':' Thread 6,5,main]] finished, busy: 0.0 secs, idle: 11.582 secs
17:13:45.988 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':' Thread 3,5,main]] finished, busy: 0.0 secs, idle: 11.584 secs
17:13:45.992 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskExecutionGraph] Timing: Executing the DAG took 11.593 secs
17:13:45.993 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Run tasks'
17:13:45.993 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Run tasks' completed
17:13:45.995 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
17:13:45.995 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
17:13:45.995 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
17:13:45.995 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
17:13:45.996 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':test'.
17:13:45.996 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > There were failing tests. See the report at: file:///C:/Users/Guilh/Downloads/SkyblockAddons-2ca6c8f03e11644cab6629f93c002bf354ff3c28/build/reports/tests/test/index.html
17:13:45.996 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
17:13:45.996 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
17:13:45.996 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.  Run with --scan to get full insights.
17:13:45.996 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
17:13:45.996 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
17:13:45.996 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger]
17:13:45.997 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 15s
17:13:45.997 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] 11 actionable tasks: 4 executed, 7 up-to-date
17:13:45.998 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Worker lease root.1 completed (0 worker(s) in use)
17:13:45.998 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 4: released lock on root.1
17:13:45.999 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Run build'
17:13:45.999 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Run build' completed
17:13:46.004 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for file content cache (C:\Users\Guilh\Downloads\SkyblockAddons-2ca6c8f03e11644cab6629f93c002bf354ff3c28\.gradle\4.10.3\fileContent)
17:13:46.005 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on file content cache (C:\Users\Guilh\Downloads\SkyblockAddons-2ca6c8f03e11644cab6629f93c002bf354ff3c28\.gradle\4.10.3\fileContent).
17:13:46.008 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for task history cache (C:\Users\Guilh\Downloads\SkyblockAddons-2ca6c8f03e11644cab6629f93c002bf354ff3c28\.gradle\4.10.3\taskHistory)
17:13:46.009 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache taskHistory.bin (C:\Users\Guilh\Downloads\SkyblockAddons-2ca6c8f03e11644cab6629f93c002bf354ff3c28\.gradle\4.10.3\taskHistory\taskHistory.bin)
17:13:46.010 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on task history cache (C:\Users\Guilh\Downloads\SkyblockAddons-2ca6c8f03e11644cab6629f93c002bf354ff3c28\.gradle\4.10.3\taskHistory).
17:13:46.017 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for Build Output Cleanup Cache (C:\Users\Guilh\Downloads\SkyblockAddons-2ca6c8f03e11644cab6629f93c002bf354ff3c28\.gradle\buildOutputCleanup)
17:13:46.017 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache outputFiles.bin (C:\Users\Guilh\Downloads\SkyblockAddons-2ca6c8f03e11644cab6629f93c002bf354ff3c28\.gradle\buildOutputCleanup\outputFiles.bin)
17:13:46.019 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on Build Output Cleanup Cache (C:\Users\Guilh\Downloads\SkyblockAddons-2ca6c8f03e11644cab6629f93c002bf354ff3c28\.gradle\buildOutputCleanup).
17:13:46.022 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for cache directory md-supplier (C:\Users\Guilh\.gradle\caches\4.10.3\md-supplier)
17:13:46.022 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on cache directory md-supplier (C:\Users\Guilh\.gradle\caches\4.10.3\md-supplier).
17:13:46.024 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for cache directory md-rule (C:\Users\Guilh\.gradle\caches\4.10.3\md-rule)
17:13:46.024 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on cache directory md-rule (C:\Users\Guilh\.gradle\caches\4.10.3\md-rule).
17:13:46.026 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 1 (avg: 0.001 secs, total: 0.001 secs)
17:13:46.027 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
17:13:46.029 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.ResolutionResultsStoreFactory] Deleted 4 resolution results binary files in 0.004 secs
17:13:46.033 [DEBUG] [org.gradle.deployment.internal.DefaultDeploymentRegistry] Stopping 0 deployment handles
17:13:46.034 [DEBUG] [org.gradle.deployment.internal.DefaultDeploymentRegistry] Stopped deployment handles
17:13:46.035 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for file hash cache (C:\Users\Guilh\Downloads\SkyblockAddons-2ca6c8f03e11644cab6629f93c002bf354ff3c28\.gradle\4.10.3\fileHashes)
17:13:46.035 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache fileHashes.bin (C:\Users\Guilh\Downloads\SkyblockAddons-2ca6c8f03e11644cab6629f93c002bf354ff3c28\.gradle\4.10.3\fileHashes\fileHashes.bin)
17:13:46.035 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache resourceHashesCache.bin (C:\Users\Guilh\Downloads\SkyblockAddons-2ca6c8f03e11644cab6629f93c002bf354ff3c28\.gradle\4.10.3\fileHashes\resourceHashesCache.bin)
17:13:46.036 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on file hash cache (C:\Users\Guilh\Downloads\SkyblockAddons-2ca6c8f03e11644cab6629f93c002bf354ff3c28\.gradle\4.10.3\fileHashes).
17:13:46.037 [DEBUG] [org.gradle.cache.internal.DefaultPersistentDirectoryStore] VCS Checkout Cache (C:\Users\Guilh\Downloads\SkyblockAddons-2ca6c8f03e11644cab6629f93c002bf354ff3c28\.gradle\vcs-1) has last been fully cleaned up 0 hours ago
17:13:46.038 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache VCS Checkout Cache (C:\Users\Guilh\Downloads\SkyblockAddons-2ca6c8f03e11644cab6629f93c002bf354ff3c28\.gradle\vcs-1) was closed 0 times.
17:13:46.038 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache VCS metadata (C:\Users\Guilh\Downloads\SkyblockAddons-2ca6c8f03e11644cab6629f93c002bf354ff3c28\.gradle\4.10.3\vcsMetadata-1) was closed 0 times.
17:13:46.042 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has finished executing the build.
17:13:46.586 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientInputForwarder] Dispatching close input message: org.gradle.launcher.daemon.protocol.CloseInput@41d172ed
17:13:46.586 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 17: dispatching class org.gradle.launcher.daemon.protocol.CloseInput
17:13:46.587 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClient] Received result Failure[value=org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':test'.] from daemon DaemonInfo{pid=34156, address=[9c59170c-d43f-46bf-9f61-0feb8e8fa398 port:57334, addresses:[/127.0.0.1, /0:0:0:0:0:0:0:1]], state=Idle, lastBusy=1607875928096, context=DefaultDaemonContext[uid=05b3771d-005f-49da-a833-5f271723d13c,javaHome=C:\Program Files\Java\jdk-11.0.9,daemonRegistryDir=C:\Users\Guilh\.gradle\daemon,pid=34156,idleTimeout=10800000,daemonOpts=--add-opens,java.base/java.util=ALL-UNNAMED,-Xmx2G,-Dfile.encoding=windows-1252,-Duser.country=FR,-Duser.language=fr,-Duser.variant]} (build should be done).
17:13:46.587 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: dispatching class org.gradle.launcher.daemon.protocol.Finished
17:13:46.588 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: connection stop

**Comment by konoashi** [comment]
I deleted test folder but now on launch there is an error:

[20:07:53] [Client thread/ERROR] [FML]: Caught exception from skyblockaddons
java.lang.NoSuchMethodError: com.google.gson.JsonParser.parseString(Ljava/lang/String;)Lcom/google/gson/JsonElement;
	at codes.biscuit.skyblockaddons.utils.Utils.loadLanguageFile(Utils.java:662) ~[Utils.class:1.6.0-beta.7]
	at codes.biscuit.skyblockaddons.utils.Utils.loadLanguageFile(Utils.java:645) ~[Utils.class:1.6.0-beta.7]
	at codes.biscuit.skyblockaddons.config.ConfigValues.loadValues(ConfigValues.java:243) ~[ConfigValues.class:1.6.0-beta.7]
	at codes.biscuit.skyblockaddons.SkyblockAddons.postInit(SkyblockAddons.java:140) ~[SkyblockAddons.class:1.6.0-beta.7]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560) ~[forge-1.8.9-11.15.1.2318-1.8.9-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211) ~[forge-1.8.9-11.15.1.2318-1.8.9-universal.jar:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189) ~[forge-1.8.9-11.15.1.2318-1.8.9-universal.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:310) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:495) [ave.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329) [ave.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

**Comment by konoashi** [comment]
the build error is caused by 

public class TextUtilsTests {
    @Test
    void formatDouble() {
        assertEquals("1", TextUtils.formatDouble(1));
        assertEquals("1.57", TextUtils.formatDouble(1.57));
        assertEquals("-5.2", TextUtils.formatDouble(-5.2));
        assertEquals("1,000", TextUtils.formatDouble(1000));
        assertEquals("2,000.95", TextUtils.formatDouble(2000.95));
        assertEquals("10,000", TextUtils.formatDouble(10000));
        assertEquals("1,000,000.9", TextUtils.formatDouble(1000000.90));
    }
}
