### ISSUE TITLE
[Bug] NPE when logging into Hypixel after disconnecting from a dungeon

### ISSUE THREAD

**Issue by FluxCapacitor2** [BiscuitDevelopment/SkyblockAddons#478]
**Describe the bug**
My game crashed after rejoining Hypixel after disconnecting from a dungeon.

**To Reproduce**
1. Join a dungeon
2. Leave the server (esc > Disconnect)
3. Log back in
4. Game crashes

I have not tested this after it happened the first time. There may be other steps involved.

**Expected behavior**
Allows you to login back into Hypixel without MC crashing.

**Screenshots**
N/A

**Crash Report**
If your game crashed, please paste your crash report here.
https://paste.gg/p/anonymous/da98e965196945dcaf7a5d17d1574d3a
Stack trace:
```java
java.lang.NullPointerException: Unexpected error
	at codes.biscuit.skyblockaddons.core.dungeons.DungeonManager.isPlayerListInfoEnabled(DungeonManager.java:279)
	at codes.biscuit.skyblockaddons.listeners.PlayerListener.onTick(PlayerListener.java:521)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_177_PlayerListener_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:331)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1624)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**System Information**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - SkyblockAddons Version: 1.6.0-beta.7

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- Patcher 1.5.1
- ChatTriggers 1.3.0
- AutoTip 3.0.1
- ModCore 0.1.47
- AutoGG 4.0.3
- Cowlection 1.8.9-0.12.0
- Danker's Skyblock Mod 1.8.5-beta7
- NotEnoughUpdates 1.7.1-REL

**Additional info**
In case your line numbers are different than mine, it appears to be caused by this line in `DungeonManager.java`:
```java
List<NetworkPlayerInfo> networkPlayerInfoList = netHandlerPlayClient.getPlayerInfoMap().stream().limit(10)
                .collect(Collectors.toList());
```

**Comment by ILikePlayingGames** [comment]
Thanks for your bug report! I'll look into it.
