### ISSUE TITLE
[Bug] Wont Load the GUI

### ISSUE THREAD

**Issue by chaseisprograming** [BiscuitDevelopment/SkyblockAddons#492]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
When I load into Hypixel SkyBlock it acts like the mod Isn't installed and I checked the mod list and it says its there.

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
I Really don't understand how this happed it was working fine like day or two ago.

**Expected behavior**
for it to load up the GUI and Be able to use the mod.

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.
[https://i.imgur.com/q3HENTX.png](url)

**System Information**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.1722
 - SkyblockAddons Version: 1.5.4

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- The 5zig Mod 3.12.6
- AutoGG 3.0
- Autotip 4.0.3
- Danker's skyblock mod 1.8.4
- FoamFix unknown
- Hypixel Toggle Chat unknown
- ItemPhysic 1.3
- Keystrokes mod 8.0.2
- Not Enough Updates 1.7-REL
- Optifine 1.8.9 i7
- Oranges Simple Mods (Only used for sprint toggle) 1.2
- Patcher 41
- Reauth 3.5.0
- Sk1er LevelHead 7.2
- Skyblock Addons 1.5.4

**Additional info**
Idea on what i think the issue is here
`[20:25:42] [Client thread/INFO] [5zig]: Loaded 0 Chats and Group Chats!
[20:25:43] [Client thread/INFO]: Connecting to mc.hypixel.net, 25565
[20:25:43] [Client thread/INFO] [SkyblockAddons Transformer]: Found 1 transformers for net.minecraft.client.gui.GuiDisconnected
[20:25:43] [Client thread/INFO] [SkyblockAddons Transformer]: Applying transformer codes.biscuit.skyblockaddons.asm.GuiDisconnectedTransformer on net.minecraft.client.gui.GuiDisconnected...
[20:25:44] [Netty Client IO #0/INFO] [FML]: Server FML protocol version 1, no additional data received
[20:25:44] [Netty Client IO #0/INFO] [FML]: Server protocol version 1
[20:25:44] [Netty Client IO #0/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, itemphysic, level_head, autotip, modcore, autogg, foamfix, keystrokesmod, notenoughupdates, orangesimplemod, patcher, reauth, skyblockaddons, publictogglechat] at SERVER
[20:25:44] [Netty Client IO #0/INFO] [FML]: Injecting existing block and item data into this client instance
[20:25:44] [Netty Client IO #0/INFO] [FML]: Applying holder lookups
[20:25:44] [Netty Client IO #0/INFO] [FML]: Holder lookups applied
[20:25:44] [Netty Client IO #0/INFO] [FML]: [Netty Client IO #0] Client side modded connection established
Jan 22, 2021 8:25:45 PM club.sk1er.mods.core.network.client.NetworkClient connect
INFO: connected to server
[20:25:45] [ModCore Thread 27/INFO] [STDOUT]: [club.sk1er.mods.core.network.client.NetworkClient:tryConnect:110]: Connection established!
Jan 22, 2021 8:25:45 PM club.sk1er.mods.core.network.client.NetworkClient sendInit
INFO: Registered and listening. Sending login sequence
[20:25:45] [Client thread/FATAL]: Error executing taskjava.util.concurrent.ExecutionException: java.lang.IllegalStateException: IPCClient (ID: 587300876440305685) is not connected!
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_271]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_271]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [g.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1014) [ave.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349) [ave.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.IllegalStateException: IPCClient (ID: 587300876440305685) is not connected!
	at com.jagrosh.discordipc.IPCClient.checkConnected(IPCClient.java:358) ~[IPCClient.class:?]
	at com.jagrosh.discordipc.IPCClient.sendRichPresence(IPCClient.java:167) ~[IPCClient.class:?]
	at com.jagrosh.discordipc.IPCClient.sendRichPresence(IPCClient.java:144) ~[IPCClient.class:?]
	at eu.the5zig.mod.discord.DiscordRPCManager.setPresence(DiscordRPCManager.java:78) ~[DiscordRPCManager.class:?]
	at eu.the5zig.mod.listener.EventListener.onServerConnect(EventListener.java:151) ~[EventListener.class:?]
	at eu.the5zig.mod.listener.EventListener.handlePluginMessage(EventListener.java:227) ~[EventListener.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handler$handleCustomPayload$zzh000(NetHandlerPlayClient.java:2013) ~[bcy.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147240_a(NetHandlerPlayClient.java:1696) ~[bcy.class:?]
	at net.minecraft.network.play.server.S3FPacketCustomPayload.func_148833_a(S3FPacketCustomPayload.java:58) ~[gg.class:?]
	at net.minecraft.network.play.server.S3FPacketCustomPayload.func_148833_a(S3FPacketCustomPayload.java:11) ~[gg.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_271]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_271]
	at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
	... 17 more`

**Comment by ILikePlayingGames** [comment]
Fixed in v1.5.5

**Comment by chaseisprograming** [comment]
Good.
