### ISSUE TITLE
[Bug] It is very difficult for me to read, but I know it had something to do with Sba and originally item drop physics. 

### ISSUE THREAD

**Issue by BroadRed** [BiscuitDevelopment/SkyblockAddons#560]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SkyblockAddonsLoadingPlugin (SkyblockAddons-1.6.0-for-MC-1.8.9.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 11/08/21 8:23 AM
Description: Tesselating block model

java.lang.ArrayIndexOutOfBoundsException: -28
	at net.minecraft.client.renderer.RegionRenderCache.func_180495_p(RegionRenderCache.java:72)
	at net.optifine.override.ChunkCacheOF.func_180495_p(ChunkCacheOF.java:147)
	at net.minecraft.block.BlockFence.func_176524_e(SourceFile:125)
	at net.minecraft.block.BlockFence.func_176221_a(SourceFile:159)
	at net.minecraft.block.Block.isSideSolid(Block.java:1105)
	at net.minecraft.block.BlockPane.canPaneConnectTo(BlockPane.java:197)
	at net.minecraft.block.BlockPane.func_176221_a(BlockPane.java:43)
	at net.optifine.ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:1648)
	at net.optifine.ConnectedTextures.isNeighbour(ConnectedTextures.java:1615)
	at net.optifine.ConnectedTextures.isNeighbour(ConnectedTextures.java:1595)
	at net.optifine.ConnectedTextures.getConnectedTextureCtmIndex(ConnectedTextures.java:1338)
	at net.optifine.ConnectedTextures.getConnectedTextureCtm(ConnectedTextures.java:825)
	at net.optifine.ConnectedTextures.getConnectedTexture(ConnectedTextures.java:578)
	at net.optifine.ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:400)
	at net.optifine.ConnectedTextures.getConnectedTextureMultiPass(ConnectedTextures.java:329)
	at net.optifine.ConnectedTextures.getConnectedTexture(ConnectedTextures.java:123)
	at net.optifine.model.BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:113)
	at net.optifine.model.BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:67)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:122)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:74)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:53)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:94)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:316)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:38)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.RegionRenderCache.func_180495_p(RegionRenderCache.java:72)
	at net.optifine.override.ChunkCacheOF.func_180495_p(ChunkCacheOF.java:147)
	at net.minecraft.block.BlockFence.func_176524_e(SourceFile:125)
	at net.minecraft.block.BlockFence.func_176221_a(SourceFile:159)
	at net.minecraft.block.Block.isSideSolid(Block.java:1105)
	at net.minecraft.block.BlockPane.canPaneConnectTo(BlockPane.java:197)
	at net.minecraft.block.BlockPane.func_176221_a(BlockPane.java:43)
	at net.optifine.ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:1648)
	at net.optifine.ConnectedTextures.isNeighbour(ConnectedTextures.java:1615)
	at net.optifine.ConnectedTextures.isNeighbour(ConnectedTextures.java:1595)
	at net.optifine.ConnectedTextures.getConnectedTextureCtmIndex(ConnectedTextures.java:1338)
	at net.optifine.ConnectedTextures.getConnectedTextureCtm(ConnectedTextures.java:825)
	at net.optifine.ConnectedTextures.getConnectedTexture(ConnectedTextures.java:578)
	at net.optifine.ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:400)
	at net.optifine.ConnectedTextures.getConnectedTextureMultiPass(ConnectedTextures.java:329)
	at net.optifine.ConnectedTextures.getConnectedTexture(ConnectedTextures.java:123)
	at net.optifine.model.BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:113)
	at net.optifine.model.BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:67)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:122)

-- Block model being tesselated --
Details:
	Block: minecraft:stained_glass[color=orange]
	Block location: World: (0,106,111), Chunk: (at 0,6,15 in 0,6; contains blocks 0,0,96 to 15,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:74)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:53)

-- Block being tesselated --
Details:
	Block type: ID #95 (tile.stainedGlass // net.minecraft.block.BlockStainedGlass)
	Block data value: 1 / 0x1 / 0b0001
	Block location: World: (0,106,111), Chunk: (at 0,6,15 in 0,6; contains blocks 0,0,96 to 15,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:94)

-- Affected level --
Details:
	Level name: MpServer
	All players: 15 total; [EntityPlayerSP['BroadRed'/138059, l='MpServer', x=117.41, y=193.50, z=145.43], EntityOtherPlayerMP['MrSalva10'/138068, l='MpServer', x=119.03, y=203.54, z=145.10], EntityOtherPlayerMP['6zsx23r3au'/71, l='MpServer', x=125.00, y=187.00, z=106.00], EntityOtherPlayerMP['e0twxe96sx'/70, l='MpServer', x=134.00, y=187.00, z=106.00], EntityOtherPlayerMP['5o9sg23tv3'/73, l='MpServer', x=137.00, y=192.00, z=148.00], EntityOtherPlayerMP['nhls8h109q'/72, l='MpServer', x=122.00, y=192.00, z=148.00], EntityOtherPlayerMP['XDFreestyleXDz'/134113, l='MpServer', x=129.34, y=187.00, z=116.16], EntityOtherPlayerMP['SvenExpe'/58867, l='MpServer', x=138.31, y=195.00, z=188.47], EntityOtherPlayerMP['p78dg1qfon'/110, l='MpServer', x=136.00, y=196.00, z=167.00], EntityOtherPlayerMP['g28jv7jy59'/74, l='MpServer', x=93.00, y=196.00, z=176.00], EntityOtherPlayerMP['4nh220zp93'/120913, l='MpServer', x=126.00, y=195.50, z=180.50], EntityOtherPlayerMP['5z479tgwpk'/120914, l='MpServer', x=133.00, y=195.50, z=180.50], EntityOtherPlayerMP['j187qvac59'/120912, l='MpServer', x=122.50, y=195.50, z=184.00], EntityOtherPlayerMP['5vqurjyjba'/123, l='MpServer', x=85.50, y=187.00, z=115.50], EntityOtherPlayerMP['9v0m5y9f50'/120915, l='MpServer', x=136.50, y=195.50, z=184.00]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 290.00,4.00,1052.00 - World: (290,4,1052), Chunk: (at 2,0,12 in 18,65; contains blocks 288,0,1040 to 303,255,1055), Region: (0,2; contains chunks 0,64 to 31,95, blocks 0,0,1024 to 511,255,1535)
	Level time: 249519545 game time, 820555 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 130 total; [EntityOtherPlayerMP['12eug045o0'/122, l='MpServer', x=38.50, y=201.00, z=-86.50], EntityOtherPlayerMP['_4am'/56801, l='MpServer', x=38.34, y=198.00, z=-6.09], EntityArmorStand['Armor Stand'/121611, l='MpServer', x=122.50, y=195.50, z=191.00], EntityOtherPlayerMP['Underpayin'/76040, l='MpServer', x=37.09, y=198.00, z=-6.28], EntityArmorStand['Armor Stand'/121613, l='MpServer', x=136.50, y=195.50, z=191.00], EntityArmorStand['Armor Stand'/121612, l='MpServer', x=122.50, y=195.25, z=191.00], EntityArmorStand['Armor Stand'/121614, l='MpServer', x=136.50, y=195.25, z=191.00], EntityOtherPlayerMP['XDFreestyleXDz'/134113, l='MpServer', x=78.91, y=198.00, z=-89.16], EntityArmorStand['Armor Stand'/37407, l='MpServer', x=126.50, y=195.00, z=195.50], EntityArmorStand['Armor Stand'/37408, l='MpServer', x=126.50, y=194.75, z=195.50], EntityArmorStand['Armor Stand'/34, l='MpServer', x=88.50, y=189.00, z=112.50], EntityCreeper['Creeper'/19234, l='MpServer', x=79.01, y=77.05, z=101.56], EntityArmorStand['Armor Stand'/35, l='MpServer', x=86.50, y=189.00, z=114.50], EntityArmorStand['Armor Stand'/121639, l='MpServer', x=129.50, y=195.75, z=196.50], EntityArmorStand['Armor Stand'/121638, l='MpServer', x=129.50, y=196.00, z=196.50], EntityCreeper['Creeper'/19242, l='MpServer', x=82.09, y=76.00, z=99.69], EntityArmorStand['Armor Stand'/122671, l='MpServer', x=85.50, y=186.75, z=115.50], EntityArmorStand['Armor Stand'/122670, l='MpServer', x=85.50, y=187.00, z=115.50], EntityOtherPlayerMP['705la65uk6'/1, l='MpServer', x=5.38, y=200.00, z=-109.22], EntityArmorStand['Armor Stand'/50, l='MpServer', x=126.50, y=157.00, z=144.50], EntityOtherPlayerMP['tl2114g643'/108, l='MpServer', x=29.00, y=202.00, z=-149.00], EntityArmorStand['Armor Stand'/55, l='MpServer', x=128.66, y=156.03, z=102.53], EntityArmorStand['Armor Stand'/39479, l='MpServer', x=102.50, y=151.00, z=143.50], EntityArmorStand['Armor Stand'/56, l='MpServer', x=130.34, y=156.03, z=102.56], EntityArmorStand['Armor Stand'/39480, l='MpServer', x=102.50, y=150.75, z=143.50], EntityOtherPlayerMP['j01ydfcnoy'/106, l='MpServer', x=35.00, y=202.00, z=-146.00], EntityOtherPlayerMP['68995e5n76'/107, l='MpServer', x=35.00, y=202.00, z=-150.00], EntityOtherPlayerMP['606j8l37b1'/109, l='MpServer', x=34.00, y=202.00, z=-141.00], EntityOtherPlayerMP['1k5y0da7zd'/103, l='MpServer', x=77.50, y=199.00, z=-110.50], EntityOtherPlayerMP['Ars_Magpie'/115884, l='MpServer', x=77.34, y=198.00, z=-90.66], EntityOtherPlayerMP['e0twxe96sx'/70, l='MpServer', x=134.00, y=187.00, z=106.00], EntityOtherPlayerMP['6zsx23r3au'/71, l='MpServer', x=125.00, y=187.00, z=106.00], EntityOtherPlayerMP['5o9sg23tv3'/73, l='MpServer', x=137.00, y=192.00, z=148.00], EntityOtherPlayerMP['nhls8h109q'/72, l='MpServer', x=122.00, y=192.00, z=148.00], EntityOtherPlayerMP['nhls8h109q'/72, l='MpServer', x=122.00, y=192.00, z=148.00], EntityOtherPlayerMP['5o9sg23tv3'/73, l='MpServer', x=137.00, y=192.00, z=148.00], EntityOtherPlayerMP['g28jv7jy59'/74, l='MpServer', x=93.00, y=196.00, z=176.00], EntityOtherPlayerMP['XDFreestyleXDz'/134113, l='MpServer', x=129.34, y=187.00, z=116.16], EntityArmorStand['Armor Stand'/138062, l='MpServer', x=117.71, y=193.33, z=145.55], EntityItem['item.item.bone'/138063, l='MpServer', x=117.71, y=193.33, z=145.55], EntityArmorStand['Armor Stand'/19279, l='MpServer', x=130.03, y=155.81, z=144.00], EntityArmorStand['Armor Stand'/138066, l='MpServer', x=119.95, y=193.33, z=145.86], EntityArmorStand['Armor Stand'/19280, l='MpServer', x=129.44, y=156.41, z=144.00], EntityOtherPlayerMP['4nh220zp93'/120913, l='MpServer', x=126.00, y=195.50, z=180.50], EntityItem['item.item.bone'/138067, l='MpServer', x=119.95, y=193.33, z=145.86], EntityArmorStand['Armor Stand'/19281, l='MpServer', x=129.03, y=156.66, z=143.97], EntityOtherPlayerMP['j187qvac59'/120912, l='MpServer', x=122.50, y=195.50, z=184.00], EntityArmorStand['Armor Stand'/138064, l='MpServer', x=119.16, y=193.33, z=143.82], EntityArmorStand['Armor Stand'/19282, l='MpServer', x=129.69, y=156.03, z=143.94], EntityOtherPlayerMP['9v0m5y9f50'/120915, l='MpServer', x=136.50, y=195.50, z=184.00], EntityItem['item.item.bone'/138065, l='MpServer', x=119.16, y=193.33, z=143.82], EntityArmorStand['Armor Stand'/19283, l='MpServer', x=86.50, y=156.00, z=136.78], EntityOtherPlayerMP['5z479tgwpk'/120914, l='MpServer', x=133.00, y=195.50, z=180.50], EntityOtherPlayerMP['c839620dn3'/104, l='MpServer', x=88.00, y=199.00, z=-108.00], EntityArmorStand['Armor Stand'/19284, l='MpServer', x=86.50, y=156.00, z=139.31], EntityOtherPlayerMP['h94xx6ioxr'/102, l='MpServer', x=88.50, y=198.00, z=-98.50], EntityOtherPlayerMP['MrSalva10'/138068, l='MpServer', x=119.03, y=203.54, z=145.10], EntityOtherPlayerMP['9i1v22ayet'/105, l='MpServer', x=87.50, y=199.00, z=-115.50], EntityOtherPlayerMP['SvenExpe'/58867, l='MpServer', x=138.31, y=195.00, z=188.47], EntityArmorStand['§8[§7Lv45§8] §cIce Walker §a888§f/§a888§c?'/139100, l='MpServer', x=56.78, y=138.97, z=147.59], EntityArmorStand['Armor Stand'/19298, l='MpServer', x=103.34, y=156.03, z=145.56], EntityArmorStand['§8[§7Lv45§8] §cIce Walker §a888§f/§a888§c?'/139104, l='MpServer', x=59.39, y=145.14, z=174.94], EntityArmorStand['Armor Stand'/19299, l='MpServer', x=101.66, y=156.03, z=145.53], EntityArmorStand['Armor Stand'/19300, l='MpServer', x=97.50, y=199.00, z=156.50], EntityArmorStand['Armor Stand'/19301, l='MpServer', x=97.50, y=199.00, z=158.50], EntityOtherPlayerMP['p78dg1qfon'/110, l='MpServer', x=136.00, y=196.00, z=167.00], EntityOtherPlayerMP['p78dg1qfon'/110, l='MpServer', x=136.00, y=196.00, z=167.00], EntityOtherPlayerMP['Crystal Sentry'/88507, l='MpServer', x=53.22, y=143.00, z=14.50], EntityOtherPlayerMP['g28jv7jy59'/74, l='MpServer', x=93.00, y=196.00, z=176.00], EntityOtherPlayerMP['4nh220zp93'/120913, l='MpServer', x=126.00, y=195.50, z=180.50], EntityOtherPlayerMP['5z479tgwpk'/120914, l='MpServer', x=133.00, y=195.50, z=180.50], EntityOtherPlayerMP['5vqurjyjba'/123, l='MpServer', x=85.50, y=187.00, z=115.50], EntityOtherPlayerMP['j187qvac59'/120912, l='MpServer', x=122.50, y=195.50, z=184.00], EntityPlayerSP['BroadRed'/138059, l='MpServer', x=117.41, y=193.50, z=145.43], EntityOtherPlayerMP['5vqurjyjba'/123, l='MpServer', x=85.50, y=187.00, z=115.50], EntityOtherPlayerMP['9v0m5y9f50'/120915, l='MpServer', x=136.50, y=195.50, z=184.00], EntityOtherPlayerMP['IsiTapier'/47297, l='MpServer', x=148.75, y=151.00, z=31.00], EntityOtherPlayerMP['Etan87'/127910, l='MpServer', x=7.91, y=205.86, z=-117.30], EntityOtherPlayerMP['Crystal Sentry'/88956, l='MpServer', x=71.69, y=137.16, z=32.50], EntityOtherPlayerMP['MrSalva10'/138068, l='MpServer', x=119.03, y=203.54, z=145.10], EntityArmorStand['Armor Stand'/37294, l='MpServer', x=134.00, y=187.00, z=106.00], EntityArmorStand['Armor Stand'/37295, l='MpServer', x=134.00, y=186.75, z=106.00], EntityArmorStand['Armor Stand'/37296, l='MpServer', x=125.00, y=187.00, z=106.00], EntityOtherPlayerMP['ConSina'/79819, l='MpServer', x=0.50, y=149.00, z=-68.50], EntityArmorStand['Armor Stand'/37297, l='MpServer', x=125.00, y=186.75, z=106.00], EntityOtherPlayerMP['Crystal Sentry'/86095, l='MpServer', x=72.69, y=137.65, z=34.50], EntityOtherPlayerMP['Crystal Sentry'/89086, l='MpServer', x=73.50, y=137.63, z=35.31], EntityOtherPlayerMP['Octavius_Black'/21229, l='MpServer', x=-95.09, y=166.00, z=-68.00], EntityArmorStand['Armor Stand'/182, l='MpServer', x=133.50, y=102.53, z=104.50], EntityArmorStand['Armor Stand'/183, l='MpServer', x=155.50, y=187.53, z=123.50], EntityOtherPlayerMP['oi34z74v6o'/65, l='MpServer', x=-10.50, y=201.00, z=-103.50], EntityOtherPlayerMP['7ed6jy9lq1'/66, l='MpServer', x=-15.50, y=201.00, z=-98.50], EntityOtherPlayerMP['w589gta73e'/67, l='MpServer', x=-79.50, y=200.00, z=-123.50], EntityOtherPlayerMP['t54es81do1'/68, l='MpServer', x=-45.50, y=200.00, z=-124.50], EntityOtherPlayerMP['8ev1ndr0l4'/87, l='MpServer', x=-30.00, y=214.00, z=-89.00], EntityArmorStand['Armor Stand'/121543, l='MpServer', x=122.50, y=195.50, z=184.00], EntityOtherPlayerMP['a19s3yq8bs'/132, l='MpServer', x=-38.00, y=200.00, z=-119.00], EntityOtherPlayerMP['makoeshoi'/90645, l='MpServer', x=120.44, y=188.00, z=-28.03], EntityOtherPlayerMP['j59630215o'/69, l='MpServer', x=-45.50, y=200.00, z=-118.50], EntityOtherPlayerMP['Crystal Sentry'/85926, l='MpServer', x=74.00, y=137.50, z=36.66], EntityArmorStand['Armor Stand'/121545, l='MpServer', x=133.00, y=195.50, z=180.50], EntityOtherPlayerMP['Crystal Sentry'/88032, l='MpServer', x=72.50, y=137.00, z=37.22], EntityArmorStand['Armor Stand'/121544, l='MpServer', x=122.50, y=195.25, z=184.00], EntityArmorStand['Armor Stand'/121547, l='MpServer', x=126.00, y=195.50, z=180.50], EntityArmorStand['§6Castle Guard'/37323, l='MpServer', x=137.00, y=192.00, z=148.00], EntityArmorStand['Armor Stand'/121546, l='MpServer', x=133.00, y=195.25, z=180.50], EntityArmorStand['§e§lCLICK'/37324, l='MpServer', x=137.00, y=191.75, z=148.00], EntityArmorStand['Armor Stand'/37325, l='MpServer', x=136.00, y=196.00, z=167.00], EntityArmorStand['Armor Stand'/121548, l='MpServer', x=126.00, y=195.25, z=180.50], EntityArmorStand['Armor Stand'/37326, l='MpServer', x=136.00, y=195.75, z=167.00], EntityArmorStand['§6Castle Guard'/37327, l='MpServer', x=122.00, y=192.00, z=148.00], EntityArmorStand['§e§lCLICK'/37328, l='MpServer', x=122.00, y=191.75, z=148.00], EntityOtherPlayerMP['Crystal Sentry'/85936, l='MpServer', x=72.84, y=137.50, z=38.69], EntityArmorStand['Armor Stand'/40659, l='MpServer', x=93.00, y=196.00, z=176.00], EntityArmorStand['§6§l§nRAFFLE BOX'/37332, l='MpServer', x=129.50, y=197.88, z=167.50], EntityArmorStand['Armor Stand'/40660, l='MpServer', x=93.00, y=195.75, z=176.00], EntityArmorStand['§e§lBRING YOUR TICKETS'/37333, l='MpServer', x=129.50, y=197.50, z=167.50], EntityArmorStand['§6§lTOTAL TICKETS: §e§l0'/37334, l='MpServer', x=129.50, y=197.13, z=167.50], EntityArmorStand['§6§l§nRAFFLE BOX'/37335, l='MpServer', x=129.50, y=197.88, z=167.50], EntityArmorStand['§e§lBRING YOUR TICKETS'/37336, l='MpServer', x=129.50, y=197.50, z=167.50], EntityArmorStand['§6§lTOTAL TICKETS: §e§l0'/37337, l='MpServer', x=129.50, y=197.13, z=167.50], EntityOtherPlayerMP['XDFreestyleXDz'/134113, l='MpServer', x=129.34, y=187.00, z=116.16], EntityArmorStand['Armor Stand'/121585, l='MpServer', x=136.50, y=195.25, z=184.00], EntityArmorStand['Armor Stand'/121584, l='MpServer', x=136.50, y=195.50, z=184.00], EntityOtherPlayerMP['SvenExpe'/58867, l='MpServer', x=138.31, y=195.00, z=188.47], EntityOtherPlayerMP['StanTheMan0369'/99203, l='MpServer', x=43.69, y=208.00, z=-21.00], EntityOtherPlayerMP['6zsx23r3au'/71, l='MpServer', x=125.00, y=187.00, z=106.00], EntityOtherPlayerMP['101ajogs10'/128, l='MpServer', x=43.50, y=177.00, z=-42.50], EntityOtherPlayerMP['e0twxe96sx'/70, l='MpServer', x=134.00, y=187.00, z=106.00], EntityOtherPlayerMP['7c3w4c873h'/114, l='MpServer', x=13.50, y=201.00, z=-148.50]]
	Retry entities: 0 total; []
	Server brand: Hypixel BungeeCord (1.0.38) <- vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:402)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:44)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 879744312 bytes (838 MB) / 1711276032 bytes (1632 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_M5 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	sidebarmod{2.0} [Sidebar Mod Revamp] ([1.8.9] Sidebar Mod Revamp.jar) 
	UCHIJA	notenoughupdates{2.0.0-REL} [NotEnoughUpdates] (NotEnoughUpdates-2.0-PRE30.2.jar) 
	UCHIJA	skyblockaddons{1.6.0} [SkyblockAddons] (SkyblockAddons-1.6.0-for-MC-1.8.9.jar) 
	Loaded coremods (and transformers): 
SkyblockAddonsLoadingPlugin (SkyblockAddons-1.6.0-for-MC-1.8.9.jar)
  codes.biscuit.skyblockaddons.tweaker.SkyblockAddonsTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: !      §7nebu§bl§7a §8[§f16§fx§8].zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 471.11
	OpenGlRenderer: NVIDIA GeForce GT 710/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by Strqtz** [comment]
Disable connected textures. Also are you using refractions 250k pack?

**Comment by BroadRed** [comment]
No I'm not using refraction's pack.
