### ISSUE TITLE
[Bug] <Crash>

### ISSUE THREAD

**Issue by Cubbro** [BiscuitDevelopment/SkyblockAddons#589]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
My game crashes when I hit the side mouse button on my inventory, and this happens because I have my 8th slot binded to button 5, so if i have locking slots on and I hit button 5 in my inventory, my game crashes. This only happens with the locking slots.

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1.Turn on locking slots
2. Set 8th key to button 5
3. Middle Click in inventory

**Expected behavior**
I didn't expect it to crash, if this is on my side my apologies.

**Screenshots/Video**
[If applicable, add screenshots, or a video to help explain your problem.](https://user-images.githubusercontent.com/70996360/149461513-2cd3ba89-ed98-4cdb-955f-94b223f471ba.mp4)

**Crash Report**
If your game crashed, please paste your crash report below.

```text
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SkyblockAddonsLoadingPlugin (SkyblockAddons-1.6.1-for-MC-1.8.9.jar)
  FMLLoadingPlugin (ModCore_Container-1.0.jar)
  PatcherTweaker (Patcher_1.6.0_-_beta_4.1.jar)
  FMLLoadingPlugin (Scrollable Tooltips-1.3 (1.8.9) (1).jar)
  ModTweaker (Patcher_1.6.0_-_beta_4.1.jar)
  Main (OldAnimationsMod v2.4.2 FORGE MC1.8.9.jar)
  PlayerAPIPlugin (PlayerAPI-1.8.9-1.0.jar)
  CTJSLoadingPlugin (ctjs-1.3.2-1.8.9 (1).jar)
  Skytils On Top (Skytils-1.1.0.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 1/13/22 10:21 PM
Description: Updating screen events

java.lang.NoSuchMethodError: net.minecraft.client.gui.inventory.GuiContainer.getSlotUnderMouse()Lnet/minecraft/inventory/Slot;
	at codes.biscuit.skyblockaddons.listeners.GuiScreenListener.onMouseClick(GuiScreenListener.java:74)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_154_GuiScreenListener_onMouseClick_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:93)
	at gg.essential.loader.stage2.EssentialLoader.addToClasspath(EssentialLoader.java:86)
	at gg.essential.loader.stage2.EssentialLoaderBase.addToClasspath(EssentialLoaderBase.java:320)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:110)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:75)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:25)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at codes.biscuit.skyblockaddons.listeners.GuiScreenListener.onMouseClick(GuiScreenListener.java:74)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_154_GuiScreenListener_onMouseClick_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiInventory

-- Affected level --
Details:
	Level name: MpServer
	All players: 6 total; [EntityPlayerSP['Cubbro_'/179621, l='MpServer', x=-48.48, y=200.00, z=-121.50], EntityOtherPlayerMP['_Mr_Squirrel_'/159678, l='MpServer', x=-41.66, y=205.97, z=-130.00], EntityOtherPlayerMP['BonnFire77'/24608, l='MpServer', x=-29.00, y=200.00, z=-134.41], EntityOtherPlayerMP['Manndrew'/161845, l='MpServer', x=-29.66, y=203.69, z=-130.47], EntityOtherPlayerMP['void_gecko'/151537, l='MpServer', x=-0.47, y=200.75, z=-126.03], EntityOtherPlayerMP['drapy'/179622, l='MpServer', x=-48.47, y=213.00, z=-121.50]]
	Chunk stats: MultiplayerChunkCache: 62, 62
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -49.00,200.00,-122.00 - World: (-49,200,-122), Chunk: (at 15,12,6 in -4,-8; contains blocks -64,0,-128 to -49,255,-113), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 250772510 game time, 626306 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 56 total; [EntityOtherPlayerMP['drapy'/179622, l='MpServer', x=-48.47, y=213.00, z=-121.50], EntityArmorStand['Armor Stand'/135, l='MpServer', x=-8.50, y=228.53, z=-134.50], EntityArmorStand['Armor Stand'/29584, l='MpServer', x=13.50, y=201.00, z=-148.50], EntityArmorStand['§8[§7Lv70§8] §cTreasure Hoarder §a21869§f/§a22000§c?'/149650, l='MpServer', x=-76.31, y=202.97, z=-65.53], EntityArmorStand['Armor Stand'/29585, l='MpServer', x=13.50, y=200.75, z=-148.50], EntityArmorStand['Armor Stand'/45462, l='MpServer', x=-3.50, y=149.00, z=-108.50], EntityArmorStand['Armor Stand'/45463, l='MpServer', x=-3.50, y=148.75, z=-108.50], EntityArmorStand['Armor Stand'/29464, l='MpServer', x=-6.50, y=201.09, z=-154.50], EntityArmorStand['Armor Stand'/11801, l='MpServer', x=-30.00, y=214.00, z=-89.00], EntityArmorStand['Armor Stand'/29465, l='MpServer', x=-6.50, y=200.84, z=-154.50], EntityArmorStand['Armor Stand'/11802, l='MpServer', x=-30.00, y=213.75, z=-89.00], EntityOtherPlayerMP['BonnFire77'/24608, l='MpServer', x=-29.00, y=200.00, z=-134.41], EntityArmorStand['§6Emissary Eliza'/11684, l='MpServer', x=-37.50, y=200.00, z=-131.50], EntityOtherPlayerMP['drapy'/179622, l='MpServer', x=-48.47, y=213.00, z=-121.50], EntityArmorStand['§e§lCLICK'/11685, l='MpServer', x=-37.50, y=199.75, z=-131.50], EntityArmorStand['Armor Stand'/38, l='MpServer', x=-11.50, y=202.00, z=-98.50], EntityArmorStand['§6Royal Guard'/11687, l='MpServer', x=-45.50, y=200.00, z=-124.50], EntityArmorStand['Armor Stand'/39, l='MpServer', x=-9.59, y=200.59, z=-102.28], EntityArmorStand['§e§lCLICK'/11688, l='MpServer', x=-45.50, y=199.75, z=-124.50], EntityItem['item.item.skull.char'/179370, l='MpServer', x=-40.16, y=200.50, z=-140.44], EntityArmorStand['Armor Stand'/40, l='MpServer', x=-9.28, y=200.41, z=-100.91], EntityArmorStand['§aGuide'/11689, l='MpServer', x=-38.00, y=200.38, z=-119.00], EntityArmorStand['Armor Stand'/41, l='MpServer', x=-9.44, y=200.38, z=-101.88], EntityArmorStand['Rhys'/11690, l='MpServer', x=-38.00, y=200.00, z=-119.00], EntityArmorStand['§e§lCLICK'/11691, l='MpServer', x=-38.00, y=199.75, z=-119.00], EntityArmorStand['§6Royal Guard'/11692, l='MpServer', x=-45.50, y=200.00, z=-118.50], EntityArmorStand['§e§lCLICK'/11693, l='MpServer', x=-45.50, y=199.75, z=-118.50], EntityArmorStand['Armor Stand'/45, l='MpServer', x=-12.50, y=202.00, z=-97.50], EntityOtherPlayerMP['Manndrew'/161845, l='MpServer', x=-29.66, y=203.69, z=-130.47], EntityArmorStand['Armor Stand'/187, l='MpServer', x=-20.50, y=206.53, z=-58.50], EntityOtherPlayerMP['_Mr_Squirrel_'/159678, l='MpServer', x=-41.66, y=205.97, z=-130.00], EntityArmorStand['§8[§7Lv83§8] §f_Mr_Squirrel_'s Rock'/159682, l='MpServer', x=-37.47, y=205.63, z=-141.31], EntityArmorStand['Armor Stand'/159680, l='MpServer', x=-37.47, y=203.44, z=-141.31], EntityArmorStand['Armor Stand'/159681, l='MpServer', x=-37.47, y=205.38, z=-141.31], EntityArmorStand['Armor Stand'/11717, l='MpServer', x=-10.50, y=201.00, z=-103.50], EntityArmorStand['Armor Stand'/11718, l='MpServer', x=-10.50, y=200.75, z=-103.50], EntityArmorStand['Armor Stand'/11719, l='MpServer', x=5.41, y=200.28, z=-109.22], EntityArmorStand['Armor Stand'/11720, l='MpServer', x=5.41, y=200.00, z=-109.22], EntityArmorStand['Armor Stand'/11721, l='MpServer', x=5.41, y=199.75, z=-109.22], EntityArmorStand['Armor Stand'/11723, l='MpServer', x=-15.50, y=201.00, z=-98.50], EntityArmorStand['Armor Stand'/11724, l='MpServer', x=-15.50, y=200.75, z=-98.50], EntityWither['§e§lPASSIVE EVENT §9§LGONE WITH THE WIND §e§lRUNNING FOR §a§l16:40'/-1235, l='MpServer', x=-15.50, y=192.03, z=-121.50], EntityPlayerSP['Cubbro_'/179621, l='MpServer', x=-48.48, y=200.00, z=-121.50], EntityOtherPlayerMP['_Mr_Squirrel_'/159678, l='MpServer', x=-41.66, y=205.97, z=-130.00], EntityOtherPlayerMP['BonnFire77'/24608, l='MpServer', x=-29.00, y=200.00, z=-134.41], EntityOtherPlayerMP['Manndrew'/161845, l='MpServer', x=-29.66, y=203.69, z=-130.47], EntityOtherPlayerMP['void_gecko'/151537, l='MpServer', x=-0.47, y=200.75, z=-126.03], EntityOtherPlayerMP['void_gecko'/151537, l='MpServer', x=-0.47, y=200.75, z=-126.03], EntityArmorStand['Armor Stand'/178166, l='MpServer', x=-18.75, y=200.38, z=-134.22], EntityCreeper['Creeper'/11765, l='MpServer', x=-34.41, y=200.50, z=-141.22], EntityArmorStand['§8[§7Lv38§8] §fSqaisheyCatNose's Rock'/178167, l='MpServer', x=-18.75, y=200.63, z=-134.22], EntityArmorStand['Armor Stand'/178165, l='MpServer', x=-18.75, y=198.44, z=-134.22], EntityArmorStand['Armor Stand'/12923, l='MpServer', x=-22.50, y=151.00, z=-79.50], EntityArmorStand['Armor Stand'/11644, l='MpServer', x=-79.50, y=200.00, z=-123.50], EntityArmorStand['Armor Stand'/12924, l='MpServer', x=-22.50, y=150.75, z=-79.50], EntityArmorStand['Armor Stand'/11645, l='MpServer', x=-79.50, y=199.75, z=-123.50]]
	Retry entities: 0 total; []
	Server brand: Hypixel BungeeCord (1.1.1) <- vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:417)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:93)
	at gg.essential.loader.stage2.EssentialLoader.addToClasspath(EssentialLoader.java:86)
	at gg.essential.loader.stage2.EssentialLoaderBase.addToClasspath(EssentialLoaderBase.java:320)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:110)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:75)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:25)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	ct.js modules: [Module{name=DeepEquals,folder=.\config\ChatTriggers\modules\DeepEquals,metadata=ModuleMetadata(name=DeepEquals, version=1.0.0, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Compare two different objects for deep equality, requires=null, helpMessage=null, ignored=null, isRequired=false)}, Module{name=DeepProxy,folder=.\config\ChatTriggers\modules\DeepProxy,metadata=ModuleMetadata(name=DeepProxy, version=2.0.0, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=Ecolsson, description=null, requires=null, helpMessage=null, ignored=null, isRequired=false)}, Module{name=DungeonUtilities,folder=.\config\ChatTriggers\modules\DungeonUtilities,metadata=ModuleMetadata(name=DungeonUtilities, version=0.9.9, entry=loader.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=null, requires=[SettingsManager, PersistentData], helpMessage=null, ignored=null, isRequired=false)}, Module{name=Elementa,folder=.\config\ChatTriggers\modules\Elementa,metadata=ModuleMetadata(name=Elementa, version=1.4.3, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Gui Library, requires=null, helpMessage=null, ignored=null, isRequired=false)}, Module{name=PersistentData,folder=.\config\ChatTriggers\modules\PersistentData,metadata=ModuleMetadata(name=PersistentData, version=1.1.3, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Easily store data that persist between game and ct reloads, requires=[DeepProxy], helpMessage=null, ignored=null, isRequired=false)}, Module{name=PersistentVariables,folder=.\config\ChatTriggers\modules\PersistentVariables,metadata=ModuleMetadata(name=PersistantVariables, version=null, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Easily create variables that persist between ct reloads, requires=[DeepEquals], helpMessage=null, ignored=null, isRequired=false)}, Module{name=Promise,folder=.\config\ChatTriggers\modules\Promise,metadata=ModuleMetadata(name=Promise, version=1.1.0, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Promise polyfill for 1.0.0, requires=[PromiseV2], helpMessage=null, ignored=null, isRequired=false)}, Module{name=PromiseV2,folder=.\config\ChatTriggers\modules\PromiseV2,metadata=ModuleMetadata(name=PromiseV2, version=1.0.4, entry=index.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=McPqndq, description=Promise polyfill, requires=null, helpMessage=null, ignored=null, isRequired=false)}, Module{name=request,folder=.\config\ChatTriggers\modules\request,metadata=ModuleMetadata(name=request, version=2.1.0, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=Ecolsson, description=A nicer alternative to XMLHttpRequest with a promise-like API. See the README.md for a full api description, requires=[requestV2], helpMessage=null, ignored=null, isRequired=false)}, Module{name=requestV2,folder=.\config\ChatTriggers\modules\requestV2,metadata=ModuleMetadata(name=requestV2, version=2.0.1, entry=index.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=Ecolsson (uploaded by McPqndq), description=A nicer alternative to XMLHttpRequest with a promise-like API. See the README.md for a full api description. (PS from McPqndq: this module is a copy paste of Ecolsson's 'request' except using a different Promise polyfill.), requires=[PromiseV2], helpMessage=null, ignored=null, isRequired=false)}, Module{name=SBInvSee,folder=.\config\ChatTriggers\modules\SBInvSee,metadata=ModuleMetadata(name=SBInvSee, version=1.0.1, entry=index.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=See the inventory contents of a hypixel skyblock player, requires=[request, PersistentData], helpMessage=null, ignored=null, isRequired=false)}, Module{name=SettingsManager,folder=.\config\ChatTriggers\modules\SettingsManager,metadata=ModuleMetadata(name=SettingsManager, version=1.2.2, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Autogenerates a settings file and gui based on the object created and registers. Example usage can be found in UseExample.js, requires=null, helpMessage=null, ignored=null, isRequired=false)}, Module{name=SkyblockCommands,folder=.\config\ChatTriggers\modules\SkyblockCommands,metadata=ModuleMetadata(name=&5&k&l00&r&3 Sky&2Block &6Commands &r&5&k&l00&r&c&o by &r&4&oDolphin0xyz, version=&3&l&k0&r&6&l&o1&3&l&o.&6&l&o4&3&l&o.&6&l&o2&r&3&l&k0, entry=main.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=&a&l&k0&r&3 Adds keybinds for most skyblock commands and fast travel warps in the vanilla controls menu. &r&a&l&k0
&r&e&l&k0&r&2 If keys conflicts with other keys things may not work and things outside this moudule may break. &r&e&l&k0
&r&b&l&k0&r&d Contact me if you find bugs, need help, or have features to suggest. My discord name is Dolphin0xyz#7887 and you can also find me on the ChatTriggers discord server. &r&b&l&k0, requires=null, helpMessage=null, ignored=null, isRequired=false)}]
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	CPU: 8x AMD Ryzen 3 3100 4-Core Processor 
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1537077464 bytes (1465 MB) / 2617245696 bytes (2496 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_I7 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version        | Source                                  |
	| ------ | --------------------- | -------------- | --------------------------------------- |
	| UCHIJA | mcp                   | 9.19           | minecraft.jar                           |
	| UCHIJA | FML                   | 8.0.99.99      | forge-1.8.9-11.15.1.2318-1.8.9.jar      |
	| UCHIJA | Forge                 | 11.15.1.2318   | forge-1.8.9-11.15.1.2318-1.8.9.jar      |
	| UCHIJA | oldanimations         | 2.4.2          | minecraft.jar                           |
	| UCHIJA | PlayerAPI             | 1.0            | minecraft.jar                           |
	| UCHIJA | essential             | 1.0.0          | Essential (forge_1.8.9).jar             |
	| UCHIJA | modcore               | 0.1.51         | Sk1er Modcore-0.1.51 (1.8.9).jar        |
	| UCHIJA | ct.js                 | 1.3.2          | ctjs-1.3.2-1.8.9 (1).jar                |
	| UCHIJA | DiscordRP             | 1.2.4          | DiscordRP-1.2.4.jar                     |
	| UCHIJA | modcore_example_mod   | 1.0            | ModCore_Container-1.0.jar               |
	| UCHIJA | patcher               | 1.6.0+beta-4.1 | Patcher_1.6.0_-_beta_4.1.jar            |
	| UCHIJA | resourcepackmanager   | 1.0            | Resource_Pack_Manager_1.1.jar           |
	| UCHIJA | text_overflow_scroll  | 1.3            | Scrollable Tooltips-1.3 (1.8.9) (1).jar |
	| UCHIJA | hypixel_auto_complete | 1.0            | Sk1er Hypixel Autocomplete Mod-1.0.jar  |
	| UCHIJA | skyblockaddons        | 1.6.1          | SkyblockAddons-1.6.1-for-MC-1.8.9.jar   |
	| UCHIJA | SkyblockExtras        | 2.1.9.4        | SkyblockExtras-2.1.9.4.jar              |
	| UCHIJA | skytils               | 1.1.0          | Skytils-1.1.0.jar                       |

	Loaded coremods (and transformers): 
SkyblockAddonsLoadingPlugin (SkyblockAddons-1.6.1-for-MC-1.8.9.jar)
  codes.biscuit.skyblockaddons.tweaker.SkyblockAddonsTransformer
FMLLoadingPlugin (ModCore_Container-1.0.jar)
  club.sk1er.mods.core.forge.ClassTransformer
PatcherTweaker (Patcher_1.6.0_-_beta_4.1.jar)
  club.sk1er.patcher.tweaker.ClassTransformer
FMLLoadingPlugin (Scrollable Tooltips-1.3 (1.8.9) (1).jar)
  club.sk1er.mods.overflowscroll.forge.ClassTransformer
ModTweaker (Patcher_1.6.0_-_beta_4.1.jar)
  club.sk1er.patcher.tweaker.other.ModClassTransformer
Main (OldAnimationsMod v2.4.2 FORGE MC1.8.9.jar)
  com.spiderfrog.main.ClassTransformer
PlayerAPIPlugin (PlayerAPI-1.8.9-1.0.jar)
  api.player.forge.PlayerAPITransformer
CTJSLoadingPlugin (ctjs-1.3.2-1.8.9 (1).jar)
  com.chattriggers.ctjs.launch.plugin.CTJSTransformer
Skytils On Top (Skytils-1.1.0.jar)
  skytils.skytilsmod.asm.SkytilsTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 497.09' Renderer: 'NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2'
	Skytils Debug Info: {HasBetterFPS=false, BetterFPS Version=NONE, Disabled Start Checks=false}
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 497.09, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: !      §fp§9rism §8[§f16§9x§8].zip, FurfSky_Overlay.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD Ryzen 3 3100 4-Core Processor 
	OptiFine Version: OptiFine_1.8.9_HD_U_I7
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 497.09
	OpenGlRenderer: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

**System Information**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
 - SkyblockAddons Version: [e.g. 1.5.2]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- ChatTriggers 1.3.2
-DiscordRP 1.2.4
-Essentials
-Modcore 1.0
-OldAnimations 2.4.2
-Optifine U_i7
-Patcher 1.6.0
-PlayerAPI 1.0
-Resource Pack Manger 1.1
-Scrollable Tooltips 1.3
-Sk1er Autocomplete 1.0
-SkyblockExtras 2.1.9.4
-Skytils 1.1.0

**Additional info**

**Comment by ILikePlayingGames** [comment]
Can you please try these recommendations from fire?
```
Possible Solutions:
- Update OptiFine from I7 to M5

Recommendations:
- Most of the time you don't need more than 2GB RAM allocated (maybe 3-4GB if you use skyblock mods). You may be able to reduce the amount of RAM allocated from 6G to 2G or 3G
- If playing on 1.8.9, PlayerAPI is unneeded since developers can use AccessTransformers instead, unless you have the outdated ToggleSneak then pretty much no other mods use this useless api.
- Update ResourcePackManager, https://www.youtube.com/watch?v=OQZFWrrEcYM.
- You should remove the ModCore container. It was only used to give players ModCore before it was integrated into mods and does nothing.
- Update TextOverflowScroll from 1.3.0 to 1.4.0
- Update HypixelAutoComplete from 1.0 to 1.1
- Update Skytils from 1.1.0 to 1.1.1
```

Also, can you please update Patcher to 1.8.0?

**Comment by My-Name-Is-Jeff** [comment]
This is from a mod conflict with OldAnimations from spiderfrog
