### ISSUE TITLE
[Error] Minecraft crashed

### ISSUE THREAD

**Issue by admoood** [BiscuitDevelopment/SkyblockAddons#690]
### Discord Username

Admood#3471

### Bug Description

Hello. 
The problem is that I install your mod in the minecraft folder and after that it does not start. I don't think that the problem is in other mods since I tried to run everything separately and nothing came out (

### SBA Version

1.7.2

### Other Installed Mods

1. BazaarNotifier-1.6.1
2. ctjs-2.1.5-1.8.9
3. Danker.s.Skyblock.Mod-1.8.7-hotfix1
4. Dungeon_Rooms-3.3.1
5. NotEnoughUpdates-2.1
6. OptiFine_1.8.9_HD_U_L5
7. Patcher-1.8.6 (1.8.9)
8. Scrollable Tooltips-1.4 (1.8.9)
9. Skytils-1.5.2
10. soopyv2forge-1.1

### Operating System

Windows11

### Crash Report

---- Minecraft Crash Report ----

WARNING: coremods are present:
  SkyblockAddonsLoadingPlugin (SkyblockAddons-1.7.0-for-MC-1.8.9.jar)
  FMLLoadingPlugin (Scrollable Tooltips-1.4 (1.8.9).jar)
  Skytils On Top (Skytils-1.5.2.jar)
  PatcherTweaker (Patcher-1.8.6 (1.8.9).jar)
  ModTweaker (Patcher-1.8.6 (1.8.9).jar)
  AsmHelperLoadingPlugin (ctjs-2.1.5-1.8.9.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 3/27/23 12:37 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at codes.biscuit.skyblockaddons.features.FetchurManager.hasFetchedToday(FetchurManager.java:82)
	at codes.biscuit.skyblockaddons.features.FetchurManager.postPersistentConfigLoad(FetchurManager.java:130)
	at codes.biscuit.skyblockaddons.config.PersistentValuesManager.loadValues(PersistentValuesManager.java:74)
	at codes.biscuit.skyblockaddons.SkyblockAddons.preInit(SkyblockAddons.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:168)
	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:114)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:110)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at codes.biscuit.skyblockaddons.features.FetchurManager.hasFetchedToday(FetchurManager.java:82)
	at codes.biscuit.skyblockaddons.features.FetchurManager.postPersistentConfigLoad(FetchurManager.java:130)
	at codes.biscuit.skyblockaddons.config.PersistentValuesManager.loadValues(PersistentValuesManager.java:74)
	at codes.biscuit.skyblockaddons.SkyblockAddons.preInit(SkyblockAddons.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:168)
	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:114)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:110)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	ChatTriggers modules: [Module{name=BeaconBeam,version=1.0.0}, Module{name=guimanager,version=0.1.7}, Module{name=PromiseV2,version=1.0.4}, Module{name=soopyAddonsData,version=0.0.1}, Module{name=soopyApis,version=0.1.17}, Module{name=SoopyV2,version=2.1.202}]
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 465739592 bytes (444 MB) / 1835532288 bytes (1750 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_L5 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version      | Source                                  |
	| ----- | --------------------- | ------------ | --------------------------------------- |
	| UCH   | mcp                   | 9.19         | minecraft.jar                           |
	| UCH   | FML                   | 8.0.99.99    | forge-1.8.9-11.15.1.2318-1.8.9.jar      |
	| UCH   | Forge                 | 11.15.1.2318 | forge-1.8.9-11.15.1.2318-1.8.9.jar      |
	| UCH   | essential             | 1.0.0        | Essential (forge_1.8.9).jar             |
	| UCH   | BazaarNotifier        | 1.6.1        | BazaarNotifier-1.6.1.jar                |
	| UCH   | chattriggers          | 2.1.5        | ctjs-2.1.5-1.8.9.jar                    |
	| UCH   | Danker's Skyblock Mod | 1.8.7        | Danker.s.Skyblock.Mod-1.8.7-hotfix1.jar |
	| UCH   | dungeonrooms          | 3.3.1        | Dungeon_Rooms-3.3.1.jar                 |
	| UCH   | notenoughupdates      | 2.1.0-REL    | NotEnoughUpdates-2.1.jar                |
	| UCH   | patcher               | 1.8.6        | Patcher-1.8.6 (1.8.9).jar               |
	| UCH   | text_overflow_scroll  | 1.4.0        | Scrollable Tooltips-1.4 (1.8.9).jar     |
	| UCE   | skyblockaddons        | 1.7.0        | SkyblockAddons-1.7.0-for-MC-1.8.9.jar   |
	| UCH   | skytils               | 1.5.2        | Skytils-1.5.2.jar                       |
	| UCH   | soopyv2forge          | 1.1          | soopyv2forge-1.1.jar                    |

	Loaded coremods (and transformers): 
SkyblockAddonsLoadingPlugin (SkyblockAddons-1.7.0-for-MC-1.8.9.jar)
  codes.biscuit.skyblockaddons.tweaker.SkyblockAddonsTransformer
FMLLoadingPlugin (Scrollable Tooltips-1.4 (1.8.9).jar)
  club.sk1er.mods.scrollabletooltips.forge.ClassTransformer
Skytils On Top (Skytils-1.5.2.jar)
  gg.skytils.skytilsmod.asm.SkytilsTransformer
PatcherTweaker (Patcher-1.8.6 (1.8.9).jar)
  club.sk1er.patcher.tweaker.ClassTransformer
ModTweaker (Patcher-1.8.6 (1.8.9).jar)
  club.sk1er.patcher.tweaker.other.ModClassTransformer
AsmHelperLoadingPlugin (ctjs-2.1.5-1.8.9.jar)
  com.chattriggers.ctjs.launch.plugin.CTJSTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 31.0.101.2111' Renderer: 'Intel(R) UHD Graphics 630'
	Skytils Debug Info: {HasBetterFPS=false, BetterFPS Version=NONE, Disabled Start Checks=false}
	Launched Version: forge-11.15.1.2318
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 630 GL version 4.6.0 - Build 31.0.101.2111, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: v14.1_16x_Hypixel_Skyblock_Pack.zip, v2.1_Dark_Skyblock_UI.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_L5
	OptiFine Build: 20191204-143016
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 31.0.101.2111
	OpenGlRenderer: Intel(R) UHD Graphics 630
	OpenGlVendor: Intel
	CpuCount: 12

**Comment by PumpkinXD** [comment]
ur sba is 1.7 0 not 1.7.2

**Comment by Xander3359** [comment]
Update to latest release and delete skyblockaddonspersistent.cfg in your config folder, that should fix the issue.
